// qwik-graphql-tailwind/src/components/branch-navigation/index.tsx
import { component$ } from '@builder.io/qwik';
import { GitBranchIcon } from '~/components/icons';
import * as styles from './branch-navigation.classNames';

interface Props {
  name: string;
  owner: string;
  path: string;
  branch?: string;
}

export const BranchNavigation = component$(({ name, owner, path, branch }: Props) => {
  const crumbs = path ? path.split('/').filter(Boolean) : [];

  return (
    <nav className={styles.container}>
      <button className={styles.btn}>
        <GitBranchIcon className={styles.btnIcon} /> {branch} <span className={styles.btnCaret}>{'\u25BC'}</span>
      </button>
      {crumbs.length > 0 && (
        <div className={styles.crumbs}>
          <a href={`/${owner}/${name}`}>
            <span className={styles.rootLink}>{name}</span>
          </a>
          <span className={styles.separator}>/</span>
          {crumbs.map((crumb, i) => {
            const isLast = i === crumbs.length - 1;

            // creates a proper GitHub url path from a repo path
            const crumbPath = crumbs.slice(0, i + 1).join('/');
            const href = `/${owner}/${name}/tree/${branch}/${crumbPath}`;

            return (
              <>
                {isLast ? (
                  <span className={styles.crumbEnd}>{crumb}</span>
                ) : (
                  <>
                    <a href={`/${href}`}>
                      <span className={styles.crumbLink}>{crumb}</span>
                    </a>
                    <span className={styles.separator}>/</span>
                  </>
                )}
              </>
            );
          })}
        </div>
      )}
    </nav>
  );
});

// expo-zustand-styled-components/src/components/Repository/BranchNavigation/BranchNavigation.tsx
import { Text, useWindowDimensions } from 'react-native';
import React, { Fragment } from 'react';
import { Link } from '@react-navigation/native';

import { GitBranchIcon } from '../../Icons';
import { colors } from '../../../utils/style-variables';

import {
  RootLink,
  CrumbEnd,
  CrumbLink,
  ButtonStyled,
  CrumbsContainer,
  NavViewContainer,
  ButtonTextStyled,
} from './BranchNavigation.styles';

interface IProps {
  name: string;
  owner: string;
  path?: string;
  branch?: string;
}

const BranchNavigation = ({ path, owner, name, branch }: IProps) => {
  const { width } = useWindowDimensions();
  const crumbs = () => path?.split('/').filter(Boolean) || [];

  // creates a proper GitHub url path from a repo path
  const hrefPath = (index: number) => {
    const crumbPath = path
      ?.split('/')
      .filter(Boolean)
      .slice(0, index + 1)
      .join('/');
    return `/${owner}/${name}/tree/${branch}/${crumbPath}`;
  };

  return (
    <NavViewContainer screenWidth={width}>
      <ButtonStyled>
        <GitBranchIcon color={colors.gray600} />
        <ButtonTextStyled>{branch}</ButtonTextStyled>
        <Text>{'\u25BC'}</Text>
      </ButtonStyled>

      {crumbs().length > 0 ? (
        <CrumbsContainer>
          <Link to={`/${owner}/${name}`}>
            <RootLink screenWidth={width}>{name}</RootLink>
          </Link>
          <Text>/</Text>

          {crumbs().map((crumb, index) => {
            if (index === crumbs().length - 1) {
              return (
                <CrumbEnd key={index} screenWidth={width}>
                  {crumb}
                </CrumbEnd>
              );
            }
            return (
              <Fragment key={index}>
                <Link to={hrefPath(index)}>
                  <CrumbLink screenWidth={width}>{name}</CrumbLink>
                </Link>
                <Text>/</Text>
              </Fragment>
            );
          })}
        </CrumbsContainer>
      ) : null}
    </NavViewContainer>
  );
};

export default BranchNavigation;
