// cra-rxjs-styled-components/src/components/repo-card/RepoCard.tsx
import { Star } from '@styled-icons/heroicons-outline';
import { Repository } from '../../interfaces/repositories.interfaces';
import PrivacyBadge from '../misc/privacy-badge';
import RepoMeta from '../repo-meta';
import {
  Aside,
  BadgeWrapper,
  Containers,
  Content,
  Description,
  Header,
  HeadingLink,
  StarBtn,
  StarIcon,
} from './RepoCard.styles';

interface RepoCardProps {
  repo: Repository;
  star?: boolean;
}

function RepoCard({ repo, star }: RepoCardProps) {
  const {
    id,
    name,
    owner,
    description,
    stargazers_count,
    forks_count,
    language,
    updated_at,
    visibility,
  } = repo;

  return (
    <Containers key={id} star={star}>
      <Content>
        <Header>
          <HeadingLink to={`/${owner.login}/${name}`}>{name}</HeadingLink>
          <BadgeWrapper>
            <PrivacyBadge visibility={visibility} />
          </BadgeWrapper>
        </Header>
        <Description>{description}</Description>
        <RepoMeta
          language={language}
          forkCount={forks_count}
          stargazerCount={stargazers_count}
          updatedAt={updated_at}
        />
      </Content>
      {star && (
        <Aside>
          <StarBtn>
            <StarIcon>
              <Star />
            </StarIcon>
            Star
          </StarBtn>
        </Aside>
      )}
    </Containers>
  );
}

export default RepoCard;

// qwik-graphql-tailwind/src/components/repo-card/repo-card.tsx
import { component$ } from '@builder.io/qwik';
import { Link } from '@builder.io/qwik-city';
import { Repo, TopRepo } from '~/utils/types';
import { PrivacyBadge } from '../privacy-badge/privacy-badge';
import { RepoMeta } from '../repo-meta/repo-meta';

interface RepoStyles {
  item: string;
  headingLink: string;
  description: string;
}

export interface RepoCardProps {
  repo: Repo | TopRepo;
  styles: RepoStyles;
}

export const RepoCard = component$(({ repo, styles }: RepoCardProps) => {
  const { id, name, owner, description, stargazerCount, forkCount, language, languageColor, updatedAt, isPrivate } =
    repo;

  return (
    <div key={id} className={styles.item}>
      <h3 className="mb-2">
        {/* <a href={`/${owner}/${name}`} className={styles.headingLink}>
          {name}
        </a> */}
        <Link href={`/${owner}/${name}`} className={styles.headingLink}>
          {name}
        </Link>
        <PrivacyBadge isPrivate={isPrivate} className="relative bottom-0.5" />
      </h3>
      <div className={styles.description}>{description}</div>
      <RepoMeta
        language={language}
        languageColor={languageColor}
        forkCount={forkCount}
        stargazerCount={stargazerCount}
        updatedAt={updatedAt}
      />
    </div>
  );
});
