// qwik-graphql-tailwind/src/routes/auth/signin/index.tsx
import { component$ } from '@builder.io/qwik';
import type { DocumentHead } from '@builder.io/qwik-city';
import { SIGN_IN_URL } from '~/utils/constants';

export default component$(() => {
  return (
    <section class="flex h-screen w-full flex-col items-center justify-center bg-black">
      <button
        class="rounded-md border-2 border-zinc-700 px-20 py-2 text-zinc-100 transition-all hover:border-zinc-100 hover:bg-zinc-100 hover:text-zinc-900"
        onClick$={() => {
          window.location.href = SIGN_IN_URL;
        }}
      >
        Sign In with GitHub
      </button>
      <div class="absolute bottom-0 flex justify-center pb-5 pt-6">
        <a target="_blank" rel="noreferrer noopener" href="https://www.netlify.com">
          <img src="https://www.netlify.com/v3/img/components/netlify-light.svg" alt="Deploys by Netlify" />
        </a>
      </div>
    </section>
  );
});

export const head: DocumentHead = {
  title: 'Authenticate with GitHub',
};

// next-react-query-tailwind/src/pages/auth/signin.tsx
/* eslint-disable @next/next/no-img-element */
import { getProviders, signIn } from 'next-auth/react';
import { InferGetServerSidePropsType } from 'next';

export default function SignIn({
  providers,
}: InferGetServerSidePropsType<typeof getServerSideProps>) {
  return (
    <>
      <section className="flex flex-col items-center w-full h-full bg-gray-900">
        {providers
          ? Object.values(providers).map((provider) => (
              <div
                key={provider.name}
                className="flex justify-center content-center h-5/6 w-11/12"
              >
                <button
                  className="self-center w-3/5 lg:w-1/5 py-5 px-2 text-white border-solid border-white border-2   rounded-sm hover:text-gray-900 hover:bg-white transition-colors"
                  onClick={() => signIn(provider.id, { callbackUrl: '/' })}
                >
                  Sign in with {provider.name}
                </button>
              </div>
            ))
          : null}

        <div className="w-11/12 pb-6">
          <a
            target="_blank"
            rel="noreferrer noopener"
            href="https://www.netlify.com"
          >
            <img
              src="https://www.netlify.com/v3/img/components/netlify-light.svg"
              alt="Deploys by Netlify"
              className="m-auto"
            />
          </a>
        </div>
      </section>
    </>
  );
}

export async function getServerSideProps() {
  const providers = await getProviders();
  return {
    props: { providers },
  };
}
