// svelte-kit-scss/src/routes/signin/+page.svelte
<script lang="ts">
  import { PUBLIC_CLIENT_REDIRECT_URL, PUBLIC_API_URL } from '$env/static/public'

  const onClick = () => {
    window.location.href = signInUrl();
  };

  const signInUrl = () => {
    const redirectUrl = getRedirectUrl();
    return `${PUBLIC_API_URL}/api/auth/signin?redirect_url=${redirectUrl}`;
  }

  /**
   * Determines the host of the page, and uses that to create a redirect url
   */
  const getRedirectUrl = () =>  {
    const prPreviewRegex = /pr-(?:\d+)+.(?:[a-z0-9]+)+.amplifyapp.com/;
    const currentUrlHost = window.location.href;
    const prMatch = prPreviewRegex.test(currentUrlHost);
    let redirectUrl: string;
    if (prMatch) {
      redirectUrl = `https://${currentUrlHost}/redirect`;
    } else {
      redirectUrl = PUBLIC_CLIENT_REDIRECT_URL;
    }
    return redirectUrl;
  }
</script>

<div class="page">
  <div class="form">
    <button type="submit" class="button" on:click={onClick}>Sign in with GitHub</button>
  </div>
</div>

<style lang="scss">
  @use 'src/lib/styles/variables';

  .page {
    position: absolute;
    width: 100%;
    height: 100%;
    overflow: hidden;
    background: variables.$black;
    color: variables.$gray500;
  }

  .form {
    width: 100%;
    height: 100%;
    display: grid;
    place-items: center;
  }

  .button {
    width: 34%;
    padding: 1rem;
    border: 1px solid variables.$gray500;
    border-radius: 0.375rem;
    font-weight: 500;
    font-size: 100%;
    background: variables.$black;
    color: variables.$gray500;
    cursor: pointer;

    &:hover {
      background: variables.$gray500;
      color: variables.$black;
    }
  }
</style>

// cra-rxjs-styled-components/src/routes/sign-in.tsx
import styled from 'styled-components';
import { useSignIn } from '../hooks/auth/use-sign-in';

const Main = styled.main`
	position: absolute;
	width: 100%;
	height: 100%;
	display: table;
	margin: 0;
	padding: 0;
`;

const Page = styled.div`
	background: black;
	display: table-cell;
	vertical-align: middle;
	text-align: center;
	padding: 0.5rem;
`;

const FormContainer = styled.div`
	max-width: 300px;
	display: block;
	margin: 0 auto 0.5rem;
`;

const SubmitButton = styled.button`
	background: transparent;
	padding: 0.75rem 1rem;
	width: 100%;
	color: #ccc;
	border: 1px solid #555;
	border-radius: 0.3rem;
	font-size: 1rem;
	font-weight: 500;
	cursor: pointer;
`;

function SignIn() {
	const handleOnSubmit = useSignIn();

	return (
		<Main>
			<Page>
				<FormContainer>
					<form method="POST" onSubmit={handleOnSubmit}>
						<input type="hidden" name="csrfToken" />
						<input type="hidden" name="callbackUrl" />
						<SubmitButton type="submit" className="button">
							Sign in with GitHub
						</SubmitButton>
					</form>
				</FormContainer>
			</Page>
		</Main>
	);
}

export default SignIn;
