// qwik-graphql-tailwind/src/components/profile-nav/profile-nav.tsx
import { component$ } from '@builder.io/qwik';
import TabNavigation from '../tab-navigation/tab-navigation';
import { tabList } from './tab-list';

interface ProfileNavProps {
  className?: string;
  basePath?: string;
  isOrg?: boolean;
  pathname: string;
}

export const ProfileNav = component$(({ className, pathname }: ProfileNavProps) => {
  return <TabNavigation tabs={tabList} className={className} pathname={pathname} />;
});

export default ProfileNav;

// remix/app/components/ProfileNav/ProfileNav.tsx
import TabNavigation from '../TabNavigation/TabNavigation';
import { tabList } from './tabList';

interface ProfileNavProps {
  className?: string;
  basePath?: string;
  isOrg?: boolean;
}

function ProfileNav({ basePath, className }: ProfileNavProps) {
  return <TabNavigation tabs={tabList} className={className} basePath={basePath} />;
}

export default ProfileNav;
