// angular-apollo-tailwind/src/app/issues/components/issues-skeleton/issues-skeleton.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-issues-skeleton',
  template: `<div
    *ngFor="let empty of emptyArray"
    class="p-4 border-b animate-pulse space-y-2"
    data-testid="skeleton"
  >
    <div class="ml-6 max-w-3xl w-full h-5 bg-gray-200 rounded"></div>
    <div class="ml-6 w-48 h-3.5 bg-gray-200 rounded"></div>
  </div>`,
})
export class IssuesSkeletonComponent {
  emptyArray = Array.from({ length: 3 });
}

// next-react-query-tailwind/src/components/IssuesSkeleton/IssuesSkeleton.tsx
export function IssuesSkeleton() {
  return (
    <div
      className="p-4 border-b animate-pulse space-y-2"
      data-testid="skeleton"
    >
      <div className="ml-6 max-w-3xl w-full h-5 bg-gray-200 rounded" />
      <div className="ml-6 w-48 h-3.5 bg-gray-200 rounded" />
    </div>
  );
}
export default IssuesSkeleton;
