// qwik-graphql-tailwind/src/components/header/header.tsx
import { component$ } from '@builder.io/qwik';
import { Link } from '@builder.io/qwik-city';
import { UserDropdown } from '../user-dropdown/userDropdown';
import { GitHubLogo } from './github-logo';

import * as styles from './header.classNames';

type HeaderProps = {
  user: {
    avatarUrl: string;
    login: string;
  } | null;
};

export default component$(({ user }: HeaderProps) => {
  return (
    <header className={styles.header}>
      <Link href="/">
        <GitHubLogo />
      </Link>
      <div>
        {user ? (
          <UserDropdown image={user.avatarUrl} username={user.login} />
        ) : (
          <Link href="/api/auth/signin">
            <span className={styles.navLink}>Sign In</span>
          </Link>
        )}
      </div>
    </header>
  );
});

// expo-zustand-styled-components/src/components/Header/Header.tsx
import React from 'react';
import { GitHubLogo } from './GitHubLogo';
import { StyledHeader } from './Header.styles';
import UserDropdown from '../UserDropdown';

const Header = () => {
  return (
    <StyledHeader>
      {/* <Link to="/"> */}
      <GitHubLogo />
      {/* </Link> */}
      <UserDropdown username={'test'} />
      {/* <Link
        to="/login"
      >
        <Text>Sign In</Text>
      </Link> */}
    </StyledHeader >
  );
};

export default Header;
