// angular-apollo-tailwind/src/app/repos/components/repo-meta/repo-meta.component.ts
import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-repo-meta',
  templateUrl: './repo-meta.component.html',
  styleUrls: ['./repo-meta.component.css'],
})
export class RepoMetaComponent {
  @Input() language: string | undefined;
  @Input() forkCount?: number = 0;
  @Input() stargazerCount?: number = 0;
  @Input() updatedAt: string | undefined;
}

<div class="flex mt-4 text-xs text-gray-600 space-x-4">
  <ng-container *ngIf="language">
    <!-- <div>
        <span
          style={{
            backgroundColor: 'w-3 h-3 inline-block rounded-full mr-1 relative top-0.5' || '#ccc',
          }}
          class="w-3 h-3 inline-block rounded-full mr-1 relative top-0.5"
        ></span>
        {{language}}
      </div> -->
  </ng-container>

  <ng-container *ngIf="stargazerCount > 0 || forkCount > 0">
    <div class="space-x-4">
      <ng-container *ngIf="stargazerCount > 0">
        <span class="hover:cursor-pointer hover:text-blue-600">
          <!-- <StarIcon class="w-4 h-4 inline mb-0.5" /> {stargazerCount}
             -->
          <hero-icon name="star" type="outline" class="btnIcon"></hero-icon>
          {{ stargazerCount }}
        </span>
      </ng-container>
      <ng-container *ngIf="forkCount > 0">
        <span class="hover:cursor-pointer hover:text-blue-600">
          <!-- <GitBranchIcon class="w-4 h-4 inline mb-0.5" /> {forkCount} -->
          <app-git-branch-icon class="btnIcon"></app-git-branch-icon>
          {{ forkCount }}
        </span>
      </ng-container>
    </div>
  </ng-container>
  <div>
    <!-- Updated{' '}
      {formatDistance(new Date(updatedAt), Date.now(), {
        addSuffix: true,
      })} -->
  </div>
</div>

// nuxt-pinia-tailwind/components/RepoMeta/RepoMeta.vue
<template>
  <div class="flex mt-4 text-xs text-gray-600 space-x-4">
    <div v-if="language">
      <span
        class="w-3 h-3 inline-block rounded-full mr-1 relative top-0.5"
        :style="{ backgroundColor: languageColor || '#ccc' }"
      >
      </span>
      {{ language }}
    </div>

    <div v-if="stargazerCount || forkCount" class="space-x-4">
      <span
        v-if="stargazerCount"
        class="hover:cursor-pointer hover:text-blue-600"
      >
        <StarIcon class="w-4 h-4 inline mb-0.5" /> {{ stargazerCount }}
      </span>

      <span v-if="forkCount" class="hover:cursor-pointer hover:text-blue-600">
        <GitBranchIcon class="w-4 h-4 inline mb-0.5" /> {{ forkCount }}
      </span>
    </div>

    <!-- <div>
        Updated{' '}
        {formatDistance(new Date(updatedAt), Date.now(), {
          addSuffix: true,
        })}
      </div> -->
  </div>
</template>
<script lang="ts">
export default {
  props: {
    language: {
      type: String,
      required: false,
      default: null,
    },
    languageColor: {
      type: String,
      required: false,
      default: null,
    },
    stargazerCount: {
      type: Number,
      required: true,
      default: 0,
    },
    forkCount: {
      type: Number,
      required: true,
      default: 0,
    },
    updatedAt: {
      type: Date,
      required: true,
      default: new Date(),
    },
  },
};
</script>
