// vue3-apollo-quasar/src/components/RepoAbout/Description.vue
<template>
  <span v-if="text">{{ text }}</span>
  <span v-else class="italic"
    >No description, website, or topics provided.</span
  >
</template>

<script lang="ts">
import { defineComponent } from 'vue';

export default defineComponent({
  name: 'Description',
  props: {
    text: String,
  },
});
</script>

// next-react-query-tailwind/src/components/RepoAboutWidget/Description.tsx
interface DescriptionProps {
  text?: string | null;
}

function Description({ text }: DescriptionProps) {
  return text ? (
    <span data-testid="repo file explorer description">{text}</span>
  ) : (
    <span className="italic" data-testid="repo file explorer description">
      No description, website, or topics provided.
    </span>
  );
}

export default Description;
