// solidjs-tailwind/src/components/BranchNavigation/BranchNavigation.jsx
import { For } from 'solid-js';
import { Link } from '@solidjs/router';
import { GitBranchIcon } from '../Icons';
import styles from './BranchNavigation.module.css';
import { useParams } from '@solidjs/router';
import { useRepo } from '../../contexts/RepoContext';

function BranchNavigation() {
  const params = useParams();
  const { info } = useRepo();

  const branch = info().branch || params.branch;

  // creates a proper GitHub url path from a repo path
  const hrefPath = (index) => {
    const crumbPath = params.path?.split('/')
      .filter(Boolean)
      .slice(0, index + 1)
      .join('/');
    return `/${params.owner}/${params.name}/tree/${branch}/${crumbPath}`;
  };

  return (
    <nav class={styles.container}>
      <button class={styles.btn}>
        <GitBranchIcon class={styles.btnIcon} /> {branch}{' '}
        <span class={styles.btnCaret}>{'\u25BC'}</span>
      </button>
      {params.path?.split('/').filter(Boolean).length > 0 && (
        <div class={styles.crumbs}>
          <Link href={`/${params.owner}/${params.name}`}>
            <a
              data-testid={`file explorer nav root ${params.name}`}
              class={styles.rootLink}
            >
              {params.name}
            </a>
          </Link>
          <span class={styles.separator}>/</span>
          <For each={params.path?.split('/').filter(Boolean)}>
            {(crumb, index) => (
              <>
                {index() ===
                params.path?.split('/').filter(Boolean).length - 1 ? (
                  <span
                    data-testid={`file explorer nav end ${crumb}`}
                    class={styles.crumbEnd}
                  >
                    {crumb}
                  </span>
                ) : (
                  <>
                    <Link href={`${hrefPath(index())}`}>
                      <a
                        data-testid={`file explorer nav crumb ${crumb}`}
                        class={styles.crumbLink}
                      >
                        {crumb}
                      </a>
                    </Link>
                    <span class={styles.separator}>/</span>
                  </>
                )}
              </>
            )}
          </For>
        </div>
      )}
    </nav>
  );
}

export default BranchNavigation;

// qwik-graphql-tailwind/src/components/branch-navigation/index.tsx
import { component$ } from '@builder.io/qwik';
import { GitBranchIcon } from '~/components/icons';
import * as styles from './branch-navigation.classNames';

interface Props {
  name: string;
  owner: string;
  path: string;
  branch?: string;
}

export const BranchNavigation = component$(({ name, owner, path, branch }: Props) => {
  const crumbs = path ? path.split('/').filter(Boolean) : [];

  return (
    <nav className={styles.container}>
      <button className={styles.btn}>
        <GitBranchIcon className={styles.btnIcon} /> {branch} <span className={styles.btnCaret}>{'\u25BC'}</span>
      </button>
      {crumbs.length > 0 && (
        <div className={styles.crumbs}>
          <a href={`/${owner}/${name}`}>
            <span className={styles.rootLink}>{name}</span>
          </a>
          <span className={styles.separator}>/</span>
          {crumbs.map((crumb, i) => {
            const isLast = i === crumbs.length - 1;

            // creates a proper GitHub url path from a repo path
            const crumbPath = crumbs.slice(0, i + 1).join('/');
            const href = `/${owner}/${name}/tree/${branch}/${crumbPath}`;

            return (
              <>
                {isLast ? (
                  <span className={styles.crumbEnd}>{crumb}</span>
                ) : (
                  <>
                    <a href={`/${href}`}>
                      <span className={styles.crumbLink}>{crumb}</span>
                    </a>
                    <span className={styles.separator}>/</span>
                  </>
                )}
              </>
            );
          })}
        </div>
      )}
    </nav>
  );
});
