// angular-apollo-tailwind/src/app/repo/repo-tab-navigation/repo-tab-navigation.component.ts
import { Component, OnInit } from '@angular/core';

export interface TabItem {
  title: string;
  path?: string;
  Icon: string;
}
@Component({
  selector: 'app-repo-tab-navigation',
  templateUrl: './repo-tab-navigation.component.html',
})
export class RepoTabNavigationComponent implements OnInit {
  constructor() {}
  tabs!: TabItem[];

  ngOnInit(): void {}
}

// const { pathname, asPath, query } = useRouter();

// const asPathBase = basePath
//   .replaceAll('[', '')
//   .replaceAll(']', '')
//   .split('/')
//   .map((part) => query[part])
//   .filter((queryPart) => typeof queryPart === 'string')
//   .join('/');

//   const isCurrentTab = (path?: string) => {
//     const matchPath = path === '' ? basePath : `${basePath}/${path}`;
//     return typeof path === undefined ? false : pathname.includes(matchPath);
//   };
<div className="border-b border-gray-200">
  <nav className="-mb-px flex" aria-label="Tabs">
    <!-- {tabList.map(({ title, path, Icon }, index) => ( -->
    <ng-container *ngFor="let tab of tabs"></ng-container>
        <a [routerLink]="tab.path ? `/${owner}/${name}/${tab.path}` : `/${owner}/${name}`"
          className={cn(
            isCurrentTab(tab.path) ? styles.tabActive : styles.tabInactive,
            styles.tab
          )}
        >
          <Icon
            className={cn(
              isCurrentTab(tab.path) ? styles.iconActive : styles.iconInactive,
              styles.icon
            )}
          />
          <span>{tab.title}</span>
        </a>
    <!-- ))} -->
  </nav>
</div>

// next-react-query/src/components/RepoTabNavigation/RepoTabNavigation.tsx
import cn from 'classnames';
import { useRepo } from '@context/RepoContext';
import Link from 'next/link';
import { useRouter } from 'next/router';
import styles from './RepoTabNavigation.module.css';
import { tabList } from './tabList';

function RepoTabNavigation() {
  const { asPath } = useRouter();
  const { owner, name } = useRepo();

  const isCurrentTab = (path?: string) =>
    typeof path === 'string' ? asPath.includes(path) : false;

  return (
    <div className={styles.container}>
      <nav className={styles.nav} aria-label="Tabs">
        {tabList.map(({ title, path, Icon }, index) => (
          <Link
            href={path ? `/${owner}/${name}/${path}` : `/${owner}/${name}`}
            key={index}
          >
            <a
              key={title}
              className={cn(
                isCurrentTab(path) ? styles.tabActive : styles.tabInactive,
                styles.tab
              )}
            >
              <Icon
                className={cn(
                  isCurrentTab(path) ? styles.iconActive : styles.iconInactive,
                  styles.icon
                )}
              />
              <span>{title}</span>
            </a>
          </Link>
        ))}
      </nav>
    </div>
  );
}

export default RepoTabNavigation;
