// angular-apollo-tailwind/src/app/repo-tab-navigation/repo-tab-navigation.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-repo-tab-navigation',
  templateUrl: './repo-tab-navigation.component.html',
  styleUrls: ['./repo-tab-navigation.component.css'],
})
export class RepoTabNavigationComponent implements OnInit {
  constructor() {}

  ngOnInit(): void {}
}

// import { useRepo } from '@context/RepoContext';

// const { asPath } = useRouter();
// const { owner, name } = useRepo();

// const isCurrentTab = (path?: string) =>
//   typeof path === 'string' ? asPath.includes(path) : false;

<div className="border-b border-gray-200">
  <nav className="-mb-px flex" aria-label="Tabs">
    {tabList.map(({ title, path, Icon }, index) => (
      <Link
        href={path ? `/${owner}/${name}/${path}` : `/${owner}/${name}`}
        key={index}
      >
        <a
          key={title}
          className={cn(
            isCurrentTab(path) ? styles.tabActive : styles.tabInactive,
            styles.tab
          )}
        >
          <Icon
            className={cn(
              isCurrentTab(path) ? styles.iconActive : styles.iconInactive,
              styles.icon
            )}
          />
          <span>{title}</span>
        </a>
      </Link>
    ))}
  </nav>
</div>

// next-react-query/src/components/RepoTabNavigation/RepoTabNavigation.tsx
import cn from 'classnames';
import { useRepo } from '@context/RepoContext';
import Link from 'next/link';
import { useRouter } from 'next/router';
import styles from './RepoTabNavigation.module.css';
import { tabList } from './tabList';

function RepoTabNavigation() {
  const { asPath } = useRouter();
  const { owner, name } = useRepo();

  const isCurrentTab = (path?: string) =>
    typeof path === 'string' ? asPath.includes(path) : false;

  return (
    <div className={styles.container}>
      <nav className={styles.nav} aria-label="Tabs">
        {tabList.map(({ title, path, Icon }, index) => (
          <Link
            href={path ? `/${owner}/${name}/${path}` : `/${owner}/${name}`}
            key={index}
          >
            <a
              key={title}
              className={cn(
                isCurrentTab(path) ? styles.tabActive : styles.tabInactive,
                styles.tab
              )}
            >
              <Icon
                className={cn(
                  isCurrentTab(path) ? styles.iconActive : styles.iconInactive,
                  styles.icon
                )}
              />
              <span>{title}</span>
            </a>
          </Link>
        ))}
      </nav>
    </div>
  );
}

export default RepoTabNavigation;
