// angular-apollo-tailwind/src/app/components/filter-dropdown/filter-dropdown.component.ts
import { trigger, transition, style, animate } from '@angular/animations';
import {
  Component,
  ElementRef,
  EventEmitter,
  HostListener,
  Input,
  Output,
} from '@angular/core';

export interface FilterOption {
  label: string;
  value: string;
}

@Component({
  selector: 'app-filter-dropdown',
  templateUrl: './filter-dropdown.component.html',
  styleUrls: ['./filter-dropdown.component.css'],
  animations: [
    trigger('openClose', [
      transition(':enter', [
        style({ opacity: 0, transform: 'scale(0.95)' }),
        animate('100ms ease-out', style({ opacity: 1, transform: 'scale(1)' })),
      ]),
      transition(':leave', [
        animate('75ms', style({ opacity: 0, transform: 'scale(0.95)' })),
      ]),
    ]),
  ],
})
export class FilterDropdownComponent {
  @Input() name = '';
  @Input() description = '';
  @Input() current: string | null = '';
  @Input() items: FilterOption[] = [];

  @Output() setFilter: EventEmitter<string> = new EventEmitter();

  isOpen = false;

  constructor(private elRef: ElementRef) {}

  toggleMenu() {
    this.isOpen = !this.isOpen;
  }

  handleSetFilterClick(label: string) {
    if (label === this.current) {
      this.setFilter.emit('');
    } else {
      this.setFilter.emit(label);
    }
    this.isOpen = false;
  }

  handleClearFilterClick() {
    this.setFilter.emit('');
    this.isOpen = false;
  }

  // TODO: maybe convert to directive
  @HostListener('document:click', ['$event'])
  onClick(event: PointerEvent) {
    if (!this.elRef.nativeElement.contains(event.target)) {
      this.isOpen = false;
    }
  }
}

<ul class="filter-dropdown-container">
  <div>
    <button
      role="button"
      class="filterButton"
      (click)="toggleMenu()"
      [attr.data-testid]="'filters dropdown ' + name"
    >
      {{ name }}
      <hero-icon
        name="chevron-down"
        type="outline"
        class="menuButtonIcon"
        aria-hidden="true"
      ></hero-icon>
    </button>
  </div>

  <div @openClose *ngIf="isOpen" class="menu" data-testid="filterDropdown">
    <div *ngIf="description">
      <div class="menuHeader">
        <div class="description">{{ description }}</div>
        <button class="flex" (click)="handleClearFilterClick()">
          <hero-icon
            name="x"
            type="outline"
            class="mr-2 h-4 w-4 text-gray-600"
            aria-hidden="true"
          ></hero-icon>
        </button>
      </div>
      <ng-container *ngFor="let item of items">
        <button
          type="button"
          class="itemButton"
          (click)="handleSetFilterClick(item.value)"
          [attr.data-testid]="'filters dropdown item ' + item.label"
        >
          <hero-icon
            *ngIf="item.value === current"
            name="check"
            type="outline"
            class="itemActiveIcon"
            aria-hidden="true"
          ></hero-icon>
          {{ item.label }}
        </button>
      </ng-container>
    </div>
  </div>
</ul>

// next-react-query-tailwind/src/components/RepoFilters/FilterDropdown.tsx
import { Fragment } from 'react';
import { Menu, Transition } from '@headlessui/react';
import { ChevronDownIcon, XIcon, CheckIcon } from '@heroicons/react/solid';
import styles from './FilterDropdown.module.css';

interface Option {
  label: string;
  value: number | string;
}

interface DropdownProps {
  name: string;
  description?: string;
  current: number | string;
  items: Option[];
  onChange: (value: any) => void;
}

function Dropdown({
  name,
  description,
  current,
  items,
  onChange,
}: DropdownProps) {
  return (
    <Menu as="div" className={styles.container}>
      <div>
        <Menu.Button
          className={styles.menuButton}
          data-testid={'filters dropdown ' + name}
        >
          {name}
          <ChevronDownIcon
            className={styles.menuButtonIcon}
            aria-hidden="true"
          />
        </Menu.Button>
      </div>
      <Transition
        as={Fragment}
        enter="transition ease-out duration-100"
        enterFrom="transform opacity-0 scale-95"
        enterTo="transform opacity-100 scale-100"
        leave="transition ease-in duration-75"
        leaveFrom="transform opacity-100 scale-100"
        leaveTo="transform opacity-0 scale-95"
      >
        <Menu.Items
          className={styles.menu}
          data-testid={'filters dropdown ' + name + ' items'}
        >
          <div>
            {description && (
              <div className={styles.menuHeader}>
                <div className={styles.description}>{description}</div>
                <Menu.Button>
                  <XIcon
                    className={styles.closeButtonIcon}
                    aria-hidden="true"
                  />
                </Menu.Button>
              </div>
            )}
            {items.map(({ label, value }) => (
              <Menu.Item key={value}>
                <button
                  type="button"
                  className={styles.itemButton}
                  onClick={() => {
                    onChange(value);
                  }}
                  data-testid={'filters dropdown item ' + label}
                >
                  {value === current && (
                    <CheckIcon className={styles.itemActiveIcon} />
                  )}{' '}
                  {label}
                </button>
              </Menu.Item>
            ))}
          </div>
        </Menu.Items>
      </Transition>
    </Menu>
  );
}

export default Dropdown;
