// next-react-query/src/pages/[owner]/[name]/blob/[branch]/[...path].tsx
import { useRouter } from 'next/router';
import RepoPage from '@components/RepoPage';
import RepoHeader from '@components/RepoHeader';
import FileViewer from '@components/FileViewer/FileViewer.data';

const RepoBranchBlob = () => {
  const { query } = useRouter();
  return (
    <RepoPage {...query}>
      <RepoHeader />
      <div className="max-w-screen-2xl mx-auto py-8 px-4">
        <div className="grid grid-cols-12 gap-8">
          <div className="col-span-12">
            <FileViewer />
          </div>
        </div>
      </div>
    </RepoPage>
  );
};

export default RepoBranchBlob;

// qwik-graphql-tailwind/src/routes/[owner]/[name]/blob/[branch]/[...path]/index.tsx
import { component$ } from '@builder.io/qwik';
import { useLocation } from '@builder.io/qwik-city';
import { BranchNavigation } from '~/components/branch-navigation';
import { FileViewer } from '~/components/file-viewer';
import { RepoHeader } from '~/components/repo-header';
import { SPECIAL_PERIOD_CHAR_URL_ENCODED_REGEX } from '~/utils/constants';

export default component$(() => {
  const { path, name, owner, branch } = useLocation().params;
  const { forkCount, watcherCount, stargazerCount } = useLocation().query;

  const _name = name.replace(SPECIAL_PERIOD_CHAR_URL_ENCODED_REGEX, '.');
  const _path = path.replace(SPECIAL_PERIOD_CHAR_URL_ENCODED_REGEX, '.');
  const _owner = owner.replace(SPECIAL_PERIOD_CHAR_URL_ENCODED_REGEX, '.');
  const _branch = branch.replace(SPECIAL_PERIOD_CHAR_URL_ENCODED_REGEX, '.');

  return (
    <div class="bg-white h-screen">
      <RepoHeader
        name={_name}
        owner={_owner}
        forkCount={forkCount || 0}
        watcherCount={watcherCount || 0}
        stargazerCount={stargazerCount || 0}
      />
      <div className="max-w-screen-2xl mx-auto md:py-8 px-4">
        <div className="grid grid-cols-12 gap-8">
          <div className="col-span-12">
            <BranchNavigation name={_name} path={_path} owner={_owner} branch={_branch} />
            <FileViewer name={_name} path={_path} owner={_owner} branch={_branch} />
          </div>
        </div>
      </div>
    </div>
  );
});
