// solidstart-tanstackquery-tailwind-modules/src/routes/[owner]/[name]/blob/[branch]/[...path]/index.tsx
import { createQuery } from '@tanstack/solid-query';
import { createEffect, createSignal } from 'solid-js';
import { useParams } from 'solid-start';
import { BranchNavigation } from '~/components/BranchNavigation';
import { RepoHeader } from '~/components/RepoHeader';
import getRepoInfo from '~/services/get-repo-info';
import { Info } from '~/types/repo-info-type';

const RepoBlob = () => {
  const params = useParams();
  const [branch, setBranch] = createSignal(params.branch);
  const [info, setInfo] = createSignal<Info>({
    isPrivate: false,
    visibility: '',
    forkCount: 0,
    description: '',
    homepageUrl: '',
    stargazerCount: 0,
    watcherCount: 0,
    openIssueCount: 0,
    topics: [],
    isOrg: false,
    openPullRequestCount: 0,
  });

  const isOwnerAndNameValid =
    typeof params.owner === 'string' && typeof params.name === 'string';

  const repoInfo = createQuery(
    () => ['repository-info', params.owner, params.name],
    () =>
      getRepoInfo(
        isOwnerAndNameValid
          ? { owner: params.owner, name: params.name }
          : { owner: '', name: '' }
      )
  );

  createEffect(() => {
    if (repoInfo.isSuccess && !repoInfo.isLoading && repoInfo.data) {
      setInfo(repoInfo.data.info);
      setBranch(repoInfo.data.branch || params.branch);
    }
  });

  return (
    <div class="bg-white h-screen">
      <RepoHeader {...info()} />
      <div class="max-w-screen-2xl mx-auto md:py-8 px-4">
        <div class="grid grid-cols-12 gap-8">
          <div class="col-span-12 md:col-span-7 xl:col-span-9">
            <BranchNavigation branch={branch()} />
            {/* FileViewer */}
          </div>
        </div>
      </div>
    </div>
  );
};

export default RepoBlob;

// qwik-graphql-tailwind/src/routes/[owner]/[name]/blob/[branch]/[...path]/index.tsx
import { component$ } from '@builder.io/qwik';
import { useLocation } from '@builder.io/qwik-city';
import { BranchNavigation } from '~/components/branch-navigation';
import { FileViewer } from '~/components/file-viewer';
import { RepoHeader } from '~/components/repo-header';
import { SPECIAL_PERIOD_CHAR_URL_ENCODED_REGEX } from '~/utils/constants';

export default component$(() => {
  const { path, name, owner, branch } = useLocation().params;
  const { forkCount, watcherCount, stargazerCount } = useLocation().query;

  const _name = name.replace(SPECIAL_PERIOD_CHAR_URL_ENCODED_REGEX, '.');
  const _path = path.replace(SPECIAL_PERIOD_CHAR_URL_ENCODED_REGEX, '.');
  const _owner = owner.replace(SPECIAL_PERIOD_CHAR_URL_ENCODED_REGEX, '.');
  const _branch = branch.replace(SPECIAL_PERIOD_CHAR_URL_ENCODED_REGEX, '.');

  return (
    <div class="bg-white h-screen">
      <RepoHeader
        name={_name}
        owner={_owner}
        forkCount={forkCount || 0}
        watcherCount={watcherCount || 0}
        stargazerCount={stargazerCount || 0}
      />
      <div className="max-w-screen-2xl mx-auto md:py-8 px-4">
        <div className="grid grid-cols-12 gap-8">
          <div className="col-span-12">
            <BranchNavigation name={_name} path={_path} owner={_owner} branch={_branch} />
            <FileViewer name={_name} path={_path} owner={_owner} branch={_branch} />
          </div>
        </div>
      </div>
    </div>
  );
});
