// solidjs-tailwind/src/components/FileViewer/FileViewer.jsx
import { createResource } from 'solid-js';
import { useParams } from '@solidjs/router';
import styles from './FileViewer.module.css';
import { useRepo } from '../../contexts/RepoContext';
import getRepoFile from '../../services/get-repo-file';
import FileCode from './FileCode';
import FileText from './FileText';
import { mapExtensionToLanguage } from './mapExtensionToLanguage';

const FileViewer = () => {
  const { info } = useRepo();
  const params = useParams();

  const branch = params.branch || info().branch;
  const path = params.path;

  const [resBlob] = createResource(`${branch}_${params.path}`, () =>
    getRepoFile({
      owner: params.owner,
      name: params.name,
      expression: `${branch}:${params.path || ''}`,
    })
  );

  const extension = path.split('.').pop();
  const language = mapExtensionToLanguage(extension);

  return (
    <>
      {resBlob.loading ? (
        <div>Loading...</div>
      ) : (
        <div class={styles.container}>
          <div class={styles.fileHeader}>
            <span
              data-testid="file viewer line count"
              class={styles.fileHeaderLines}
            >
              {resBlob().text?.split('\n').length} lines
            </span>
            <span
              data-testid="file viewer byte size"
              class={styles.fileHeaderBytes}
            >
              {resBlob().byteSize} Bytes
            </span>
          </div>
          {language ? (
            <FileCode text={resBlob().text} language={language} />
          ) : (
            <FileText text={resBlob().text} />
          )}
        </div>
      )}
    </>
  );
};

export default FileViewer;

// expo-zustand-styled-components/src/components/FileViewer/FileViewer.tsx
import { useEffect } from 'react';
import { Text } from 'react-native';

import { useRepoInfoStore } from '../../hooks/stores';
import getRepoFile from '../../services/get-repo-file';

import { mapExtensionToLanguage } from './mapExtensionToLanguage';
import { fontFamily } from './font';

import FIleCode from './FIleCode';
import FileText from './FileText';

import { ByteSize, Containter, Header, LineCount } from './FileViewer.styles';

const FileViewer = ({ path, branch }: { path: string; branch: string }) => {
  const { file, name, owner } = useRepoInfoStore();

  useEffect(() => {
    getRepoFile({
      owner,
      name,
      expression: `${branch}:${path || ''}`,
    });
  }, [owner, name, branch, path]);

  const extension = path?.split('.').pop();
  const language = mapExtensionToLanguage(extension);

  return (
    <Containter>
      <Header>
        <LineCount style={{ fontFamily }}>{file?.text?.split('\n')?.length || 0} lines</LineCount>
        <ByteSize>
          <Text style={{ fontFamily }}>{file?.byteSize || 0} Bytes</Text>
        </ByteSize>
      </Header>

      {language ? (
        <FIleCode text={file?.text || ''} language={language} />
      ) : (
        <FileText text={file?.text} />
      )}
    </Containter>
  );
};

export default FileViewer;
