// solidstart-tanstackquery-tailwind-modules/src/routes/index.tsx
import { Switch, Match, createEffect } from 'solid-js';
import { createQuery } from '@tanstack/solid-query';
import getGists from '~/services/get-gists';
import { GistsData } from '~/components/GistPanel';
import TopRepos from '~/components/TopRepos/TopRepos';
import getTopRepos from '~/services/get-top-repos';
import { LoadingPulseDot } from '~/components/LoadingPulseDot/LoadingPulseDot';

const Home = () => {
  const gists = createQuery(() => ['gists'], getGists);
  const topRepos = createQuery(() => ['topRepos'], getTopRepos);

  createEffect(() => {
  console.log('topRepos.data?.repos', topRepos.data?.repos);
  });

  return (
    <div class="w-full min-h-[calc(100vh-70px)] flex flex-col-reverse lg:flex-row bg-gray-100">
      <aside class="w-full lg:w-96 bg-white p-8">
        <Switch>
          <Match when={gists.isError}>
            <p>Error</p>
          </Match>
          <Match when={gists.isLoading}>
            <LoadingPulseDot />
          </Match>
          <Match when={gists.isSuccess && !gists.isLoading}>
            <GistsData gists={gists.data || []} />
          </Match>
        </Switch>
      </aside>
      <main class="max-w-screen-lg w-full">
        <div class="p-12">
          <Switch>
            <Match when={topRepos.isError}>
              <p>Error</p>
            </Match>
            <Match when={topRepos.isLoading}>
              <LoadingPulseDot />
            </Match>
            <Match when={topRepos.isSuccess && !topRepos.isLoading}>
              <h2 class="text-lg font-medium mb-4">Top Repositories</h2>
              <TopRepos
                topRepos={topRepos.data?.repos || []}
                login={topRepos.data?.login || ''}
              />
            </Match>
          </Switch>
        </div>
      </main>
    </div>
  );
};

export default Home;

// remix/app/routes/index.tsx
import type { ActionFunction, LoaderFunction } from 'remix';
import { Form, json, useLoaderData } from 'remix';
import type { GitHubProfile } from 'remix-auth-github';
import { auth } from '~/services/auth.server';

type LoaderData = { profile: GitHubProfile };

export const action: ActionFunction = async ({ request }) => {
  await auth.logout(request, { redirectTo: '/login' });
};

export const loader: LoaderFunction = async ({ request }) => {
  const { profile } = await auth.isAuthenticated(request, {
    failureRedirect: '/login',
  });

  return json<LoaderData>({ profile });
};

export default function Screen() {
  const { profile } = useLoaderData<LoaderData>();
  console.log(profile);
  return (
    <div className="w-full  min-h-[calc(100vh-70px)] flex flex-col-reverse lg:flex-row bg-gray-100">
      <aside className="w-full lg:w-96 bg-white p-8">
        <p>User Gists go here</p>
      </aside>
      <main className="max-w-screen-lg w-full">
        <div className="p-12">
          <Form method="post" className='text-right'>
            <button>Log Out</button>
          </Form>
          <h2 className="text-lg font-medium mb-4">Top Repositories</h2>
          <p>User Top Repos Go Here</p>
        </div>
      </main>
    </div>
  );
}
