// qwik-graphql-tailwind/src/components/repo-heading/index.tsx
import { component$ } from '@builder.io/qwik';
import { RepoIcon } from '../icons/repo.icon';

interface RepoHeadingProps {
  name: string;
  owner: string;
}

export const RepoHeading = component$(({ name, owner }: RepoHeadingProps) => {
  const profile_url = `/${owner}`;
  const repo_url = `/${owner}/${name}`;
  return (
    <h1 className="flex items-center text-xl leading-7">
      <RepoIcon className="w-6 h-6 text-gray-600" />
      <span className="text-[#2563EB] inline-block ml-2.5 mb-0.5">
        <a>{owner}</a>
        <a href={profile_url} className="hover:underline">
          {owner}
        </a>
        <span className="text-black ml-1.5">/</span>
        <a className="font-semibold ml-1.5">{name}</a>
        <a href={repo_url} className="font-semibold ml-1.5 hover:underline">
          {name}
        </a>
      </span>
    </h1>
  );
});

// angular-apollo-tailwind/src/app/repos/repo-header/repo-heading/repo-heading.component.ts
import { Component, Input } from '@angular/core';
@Component({
  selector: 'app-repo-heading',
  templateUrl: './repo-heading.component.html',
  styleUrls: ['./repo-heading.component.css'],
})
export class RepoHeadingComponent {
  @Input() owner = '';
  @Input() name = '';
  @Input() isPrivate = false;
}

<h1 class="space-x-2.5 flex items-center text-xl">
  <app-privacy-icon
    [isPrivate]="detail?.repository?.isPrivate"
  ></app-privacy-icon>
  <span class="space-x-1.5 mb-0.5">
    <a class="text-blue-600 hover:underline">{{ detail?.owner }}</a>
    <span class="text-gray-600">/</span>
    <a [routerLink]="[detail?.owner, detail?.name]">
      <a class="text-blue-600 font-semibold hover:underline">{{
        detail?.name
      }}</a>
    </a>
  </span>
  <app-privacy-badge
    class="pb-1"
    [isPrivate]="detail?.repository?.isPrivate"
  ></app-privacy-badge>
</h1>
