// cra-rxjs-styled-components/src/components/repo-filter/SearchInput.tsx
import { useRepoFilter } from '../../context/RepoFilterContext';
import { SearchTextInput } from './RepoFilter.styles';

export default function SearchInput() {
	const { search, setSearch } = useRepoFilter();

	const handleChange = (e: any) => {
		setSearch(e.target.value);
	};
	return (
		<SearchTextInput
			role="search"
			type="search"
			name="search"
			id="search"
			placeholder="Find a repository..."
			value={search}
			onInput={handleChange}
		/>
	);
}

// qwik-graphql-tailwind/src/components/search-input/search-input.tsx
import { $, component$, useContext } from '@builder.io/qwik';
import cn from 'classnames';
import filterStore from '~/context/repo-filter';
import * as styles from './search-input.classNames';

export interface SearchInputProps {
  placeholder: string;
  className?: string;
}

export const SearchInput = component$(({ placeholder, className }: SearchInputProps) => {
  const searchValue = useContext(filterStore);
  const handleInput$ = $((e: any) => (searchValue.search = e.target.value));
  return (
    <input
      role="search"
      type="search"
      name="search"
      id="search"
      value={searchValue.search}
      className={cn(styles.input, className)}
      placeholder={placeholder}
      onInput$={handleInput$}
    />
  );
});
