// solidstart-tanstackquery-tailwind-modules/src/components/RepoMeta/RepoMeta.tsx
import { formatDistance } from 'date-fns';
import { GitBranchIcon, StarIcon } from '../Icons';
import styles from './RepoMeta.module.css';
import { splitProps } from 'solid-js';

interface RepoMetaProps {
  language: string,
  languageColor: string,
  stargazerCount: number,
  forkCount: number,
  updatedAt: string
}

const RepoMeta = (props: RepoMetaProps) => {
  const [local] = splitProps(props, ['language', 'languageColor', 'stargazerCount', 'forkCount', 'updatedAt']);

  return (
    <div class={styles.metadata}>
      {local.language && (
        <div>
          <span
            style={{
              'background-color': local.languageColor || '#ccc',
            }}
            class={styles.languageColor}
          />
          {local.language}
        </div>
      )}
      {(local.stargazerCount > 0 || local.forkCount > 0) && (
        <div class="space-x-4">
          {local.stargazerCount > 0 && (
            <span
              class={styles.socialCount}
              data-testid="repository star count"
            >
              <StarIcon class={styles.socialIcon} /> {local.stargazerCount}
            </span>
          )}
          {local.forkCount > 0 && (
            <span
              class={styles.socialCount}
              data-testid="repository fork count"
            >
              <GitBranchIcon class={styles.socialIcon} /> {local.forkCount}
            </span>
          )}
        </div>
      )}
      <div>
        Updated{' '}
        {formatDistance(new Date(local.updatedAt), Date.now(), {
          addSuffix: true,
        })}
      </div>
    </div>
  );
};

export default RepoMeta;

// next-react-query-tailwind/src/components/RepoMeta/RepoMeta.tsx
import { formatDistance } from 'date-fns';
import { StarIcon } from '@heroicons/react/24/outline';
import { GitBranchIcon } from '@components/Icons';
import styles from './RepoMeta.module.css';

interface RepoMetaProps {
  language?: string | null;
  languageColor?: string | null;
  stargazerCount: number;
  forkCount: number;
  updatedAt: Date;
}

function RepoMeta({
  language,
  languageColor,
  stargazerCount,
  forkCount,
  updatedAt,
}: RepoMetaProps) {
  return (
    <div className={styles.metadata}>
      {language && (
        <div data-testid="repository language">
          <span
            style={{
              backgroundColor: languageColor || '#ccc',
            }}
            className={styles.languageColor}
          />
          {language}
        </div>
      )}
      {(stargazerCount > 0 || forkCount > 0) && (
        <div className="space-x-4">
          {stargazerCount > 0 && (
            <span
              className={styles.socialCount}
              data-testid="repository star count"
            >
              <StarIcon className={styles.socialIcon} /> {stargazerCount}
            </span>
          )}
          {forkCount > 0 && (
            <span
              className={styles.socialCount}
              data-testid="repository fork count"
            >
              <GitBranchIcon className={styles.socialIcon} /> {forkCount}
            </span>
          )}
        </div>
      )}
      <div>
        Updated{' '}
        {formatDistance(new Date(updatedAt), Date.now(), {
          addSuffix: true,
        })}
      </div>
    </div>
  );
}

export default RepoMeta;
