// solidstart-tanstackquery-tailwind-modules/src/components/RepoActionButtons/RepoActionButtons.tsx
import styles from './RepoActionButtons.module.css';
import CountButtonGroup from './CountButtonGroup';
import { EyeIcon, StarIcon, GitBranchIcon } from '../Icons';
import { splitProps } from 'solid-js';

type RepoActionButtonsProps = {
  watcherCount: number;
  stargazerCount: number;
  forkCount: number;
};

function RepoActionButtons(props: RepoActionButtonsProps) {
  const [local] = splitProps(props, [
    'forkCount',
    'stargazerCount',
    'watcherCount',
  ]);

  return (
    <div class={styles.container}>
      <CountButtonGroup count={local.watcherCount}>
        <EyeIcon class={styles.btnIcon} />
        Watch
      </CountButtonGroup>
      <CountButtonGroup count={local.stargazerCount}>
        <StarIcon class={styles.btnIcon} />
        Star
      </CountButtonGroup>
      <CountButtonGroup count={local.forkCount}>
        <GitBranchIcon class={styles.btnIcon} />
        Fork
      </CountButtonGroup>
    </div>
  );
}

export default RepoActionButtons;

// next-react-query-tailwind/src/components/RepoActionButtons/RepoActionButtons.tsx
import { EyeIcon, GitBranchIcon } from '@components/Icons';
import { StarIcon } from '@heroicons/react/outline';
import { useRepo } from '@context/RepoContext';
import CountButtonGroup from './CountButtonGroup';
import styles from './RepoActionButtons.module.css';

function RepoActionButtons() {
  const { data } = useRepo();
  return (
    <div className={styles.container}>
      <CountButtonGroup count={data?.watcherCount}>
        <EyeIcon className={styles.btnIcon} />
        Watch
      </CountButtonGroup>
      <CountButtonGroup count={data?.stargazerCount}>
        <StarIcon className={styles.btnIcon} />
        Star
      </CountButtonGroup>
      <CountButtonGroup count={data?.forkCount}>
        <GitBranchIcon className={styles.btnIcon} />
        Fork
      </CountButtonGroup>
    </div>
  );
}

export default RepoActionButtons;
