// solidstart-tanstackquery-tailwind-modules/src/components/RepoFilter/RepoFilter.tsx
import { createSignal, mergeProps, Show } from 'solid-js';
import { RepoBookIcon } from '../Icons';
import { FILTER_TYPE_OPTIONS, SORT_OPTIONS } from './data';
import FilterDropdown from '../FilterDropDown/FilterDropdown';
import FilterText from './FilterText';
import {
  language,
  setLanguage,
  filterType,
  setFilterType,
  sortBy,
  setSortBy,
} from './RepoFilter.store';
import SearchInput from './SearchInput';
import styles from './RepoFilter.module.css';

type RepoFilterProps = {
  repoBtnText?: string;
  languages: string[];
  filteredRepoCount: number;
};

const RepoFilter = (props: RepoFilterProps) => {
  const typeOptions = Object.values(FILTER_TYPE_OPTIONS);
  const sortOptions = Object.values(SORT_OPTIONS);
  const languageOptions = ['All', 'HTML', 'CSS', 'PHP'];
  const [isOnlySorted] = createSignal(true);

  const merged = mergeProps(
    { repoBtnText: 'New', languages: languageOptions, filteredRepoCount: 0 },
    props
  );

  const selectLanguage = () => null;
  const selectType = () => null;
  const selectSort = (value: string) => setSortBy(value);

  return (
    <>
      <div class={styles.repoFilterContainer}>
        <div class={styles.filterDropDownContainer}>
          <div class="flex-grow">
            <SearchInput />
          </div>
          <div class={styles.filterDropdownList}>
            <FilterDropdown
              name="Type"
              items={typeOptions}
              selected={filterType()}
              selectOption={selectType}
            />
            <FilterDropdown
              name="Language"
              selected={language()}
              items={merged.languages}
              selectOption={selectLanguage}
            />
            <FilterDropdown
              name="Sort"
              selected={sortBy()}
              items={sortOptions}
              selectOption={selectSort}
            />
          </div>
        </div>
        <div>
          <a href="https://github.com/new" class={styles.iconLink}>
            <RepoBookIcon />
            <span> {merged.repoBtnText} </span>
          </a>
        </div>
      </div>
      <Show when={!isOnlySorted()}>
        <FilterText
          filteredRepoCount={merged.filteredRepoCount}
          setFilterType={setFilterType}
          setLanguage={setLanguage}
        />
      </Show>
    </>
  );
};

export default RepoFilter;

// expo-zustand-styled-components/src/components/RepoFilter/RepoFilter.tsx
import { useWindowDimensions } from 'react-native';
import React, { useState } from 'react';
import SearchInput from './SearchInput';
import FilterDropdown from '../FilterDropdown';
import { RepoFilterWrapper, FiltersWrapper, RepoBtn, RepoBtnText } from './RepoFilter.styles';
import { FILTER_TYPE_OPTIONS, SORT_OPTIONS } from './data';
import { useRepoFilterStore } from '../../hooks/stores';
import RepoBookIcon from '../Icons/RepoBookIcon';
import FilterText from './FilterText';

interface RepoFilterProps {
  languages: string[];
  filteredRepoCount: number;
  repoBtnText?: string;
}
const RepoFilter = ({ languages, filteredRepoCount, repoBtnText }: RepoFilterProps) => {
  const { width } = useWindowDimensions();

  const typeOptions = Object.values(FILTER_TYPE_OPTIONS);
  const sortOptions = Object.values(SORT_OPTIONS);
  const languageOptions = ['All', 'HTML', 'CSS', 'PHP']; //To be replaced with the actual languages for the repos
  const { language, sortBy, filterType, setLanguage, setSortBy, setFilterType } =
    useRepoFilterStore();
  const [showOptions, setShowOptions] = useState(null);

  const selectLanguage = (value) => setLanguage(value);
  const selectType = (value) => setFilterType(value);
  const selectSort = (value) => setSortBy(value);

  return (
    <>
      <RepoFilterWrapper screenWidth={width}>
        <SearchInput />
        <FiltersWrapper screenWidth={width}>
          <FilterDropdown
            name="Type"
            items={typeOptions}
            selectOption={selectType}
            zIndex={2000}
            selected={filterType}
            showOptions={showOptions}
            setShowOptions={(value) => setShowOptions(value)}
          />
          <FilterDropdown
            name="Sort"
            items={sortOptions}
            selectOption={selectSort}
            zIndex={1000}
            selected={sortBy}
            showOptions={showOptions}
            setShowOptions={(value) => setShowOptions(value)}
          />
          <FilterDropdown
            name="Langauge"
            items={languageOptions}
            selectOption={selectLanguage}
            zIndex={500}
            selected={language}
            showOptions={showOptions}
            setShowOptions={(value) => setShowOptions(value)}
          />
        </FiltersWrapper>
        <RepoBtn activeOpacity={0.8}>
          <RepoBookIcon color={'#FFF'} />
          <RepoBtnText>{repoBtnText || 'New'}</RepoBtnText>
        </RepoBtn>
      </RepoFilterWrapper>
      {/* Should show when repos are not just sorted */}
      <FilterText filteredRepoCount={filteredRepoCount} />
    </>
  );
};

export default RepoFilter;
