// solidstart-tanstackquery-tailwind-modules/src/components/RepoFilter/SearchInput.tsx
import styles from './RepoFilter.module.css';
import { JSX } from 'solid-js';
import { setSearch } from './RepoFilter.store';

const SearchInput = () => {
  const handleChange: JSX.EventHandler<HTMLInputElement, KeyboardEvent> = (e: KeyboardEvent) => {
    setSearch((e.target as HTMLInputElement).value || '');
  };

  return (
    <input
      data-testid="search-input"
      placeholder="find a repository.."
      role="search"
      type="search"
      onKeyUp={handleChange}
      class={styles.searchInput}
    />
  );
};

export default SearchInput;

// expo-zustand-styled-components/src/components/RepoFilter/SearchInput.tsx
import React from 'react';
import { SearchTextInput } from './RepoFilter.styles';
import { useRepoFilterStore } from '../../hooks/stores';

const SearchInput = () => {
  const { search, setSearch } = useRepoFilterStore();
  const handleOnChangeText = (value: string) => {
    setSearch(value);
  };
  return (
    <SearchTextInput
      value={search}
      placeholder="Find a repository..."
      onChangeText={handleOnChangeText}
      clearButtonMode="while-editing"
    />
  );
};

export default SearchInput;
