// next-react-query-tailwind/src/components/IssuesEmpty/IssuesEmpty.tsx
import type { ComponentType } from 'react';
import styles from './IssuesEmpty.module.css';

interface IssuesEmptyProps {
  Icon?: ComponentType<{ className: string }>;
}

function IssuesEmpty({ Icon }: IssuesEmptyProps) {
  return (
    <div className={styles.container} data-testid="issues-empty">
      {Icon && <Icon className={styles.icon} />}
      <h3 className={styles.heading}>No results matched your search.</h3>
    </div>
  );
}

export default IssuesEmpty;

// angular-apollo-tailwind/src/app/issues/components/issues-empty/issues-empty.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-issues-empty',
  template: `<div class="container" data-testid="issues-empty">
    <!-- {MinusCircleIcon && <MinusCircleIcon class="icon" />} -->
    <h3 class="heading">No results matched your search.</h3>
  </div>`,
  styleUrls: ['./issues-empty.component.css'],
})
export class IssuesEmptyComponent {}
