// next-react-query-tailwind/src/components/RepoAboutWidget/HomepageUrl.tsx
import Link from 'next/link';
import { LinkIcon } from '@heroicons/react/24/outline';
import styles from './RepoAboutWidget.module.css';

interface HomepageUrlProps {
  homepageUrl?: string | null;
}

function HomepageUrl({ homepageUrl }: HomepageUrlProps) {
  if (!homepageUrl) {
    return null;
  }

  return (
    <div className={styles.linkContainer}>
      <LinkIcon className={styles.linkIcon} />
      <Link href={homepageUrl} className={styles.link} target="_blank">
        {homepageUrl}
      </Link>
    </div>
  );
}

export default HomepageUrl;

// solidstart-tanstackquery-tailwind-modules/src/components/RepoAbout/HomePageUrl.tsx
import { Show } from 'solid-js';
import { A } from 'solid-start';
import { LinkIcon } from '../Icons';
import styles from './RepoAbout.module.css';

interface HomepageUrlProps {
  homepageUrl: string;
}

export const HomepageUrl = (props: HomepageUrlProps) => {
  return (
    <Show when={props.homepageUrl}>
      <div class={styles.linkContainer}>
        <LinkIcon class={styles.linkIcon} />
        <A href={props.homepageUrl} class={styles.link} target="_blank">
          {props.homepageUrl}
        </A>
      </div>
    </Show>
  );
};
