// qwik-graphql-tailwind/src/components/repo-about/index.tsx
import { component$, useContext } from '@builder.io/qwik';
import { RepoContext } from '~/routes/[owner]/[name]';
import { BookOpenIcon } from '../icons/book-open.icon';
import { Description } from './description';
import { HomepageUrl } from './homepage-url';
import { Topics } from './topic';
import * as styles from './repo-about.className';

export const RepoAboutWidget = component$(() => {
  const store = useContext(RepoContext);

  return (
    <div className={styles.container}>
      <h3 className={styles.heading}>About</h3>
      <div className={styles.description}>
        <div className="space-y-4">
          <Description text={store.info.data?.description} />
          <HomepageUrl homepageUrl={store.info.data?.homepageUrl} />
          <Topics topics={store.info.data?.topics} />
        </div>
      </div>
      <div>
        <a className={styles.readmeLink}>
          <BookOpenIcon className={styles.readmeIcon} /> Readme
        </a>
      </div>
    </div>
  );
});

// solidstart-tanstackquery-tailwind-modules/src/components/RepoAbout/RepoAbout.tsx
import { BookOpenIcon } from '../Icons';
import { Description } from './Description';
import { HomepageUrl } from './HomePageUrl';
import { Topics } from './Topics';

import styles from './RepoAbout.module.css';
import { splitProps } from 'solid-js';

interface Props {
  description: string;
  homepageUrl: string;
  topics: string[];
}

export const RepoAboutWidget = (props: Props) => {
  const [local] = splitProps(props, ['description', 'homepageUrl', 'topics']);

  return (
    <div class={styles.container}>
      <h3 class={styles.heading}>About</h3>
      <div class={styles.description}>
        <div data-testid="about-info" class="space-y-4">
          <Description text={local.description} />
          <HomepageUrl homepageUrl={local.homepageUrl} />
          <Topics topics={local.topics} />
        </div>
      </div>
      <div>
        <span class={styles.readmeLink}>
          <BookOpenIcon class={styles.readmeIcon} /> Readme
        </span>
      </div>
    </div>
  );
};

export default RepoAboutWidget;
