// next-react-query-tailwind/src/components/RepoAboutWidget/Topics.tsx
import styles from './RepoAboutWidget.module.css';

interface TopicsProps {
  topics?: string[];
}

function Topics({ topics }: TopicsProps) {
  if (!topics) {
    return null;
  }

  return (
    <div className="space-y-1">
      {topics.map((topic) => (
        <span key={topic} className={styles.topic}>
          {topic}
        </span>
      ))}
    </div>
  );
}

export default Topics;

// solidstart-tanstackquery-tailwind-modules/src/components/RepoAbout/Topics.tsx
import { For } from 'solid-js';
import styles from './RepoAbout.module.css';

interface TopicsProps {
  topics: string[];
}

export const Topics = (props: TopicsProps) => {
  return (
    <>
      {props.topics.length === 0 ? null : (
        <div class="space-y-1">
          <For each={props.topics}>
            {(topic) => <span class={styles.topic}>{topic}</span>}
          </For>
        </div>
      )}
    </>
  );
};
