// next-react-query-tailwind/src/components/RepoAboutWidget/Description.tsx
interface DescriptionProps {
  text?: string | null;
}

function Description({ text }: DescriptionProps) {
  return text ? (
    <span data-testid="repo file explorer description">{text}</span>
  ) : (
    <span className="italic" data-testid="repo file explorer description">
      No description, website, or topics provided.
    </span>
  );
}

export default Description;

// qwik-graphql-tailwind/src/components/repo-about/description/index.tsx
import { component$ } from '@builder.io/qwik';

interface DescriptionProps {
  text?: string | null;
}

export const Description = component$(({ text }: DescriptionProps) => {
  return text ? (
    <span data-testid="repo file explorer description">{text}</span>
  ) : (
    <span className="italic" data-testid="repo file explorer description">
      No description, website, or topics provided.
    </span>
  );
});
