// solidstart-tanstackquery-tailwind-modules/src/routes/[owner]/[name]/index.tsx
import { Switch, Match, createSignal, createEffect } from 'solid-js';
import { createQuery } from '@tanstack/solid-query';
import { useParams } from 'solid-start';
import getRepoInfo from '~/services/get-repo-info';
import { LoadingPulseDot } from '~/components/LoadingPulseDot/LoadingPulseDot';
import { Info } from '~/types/repo-info-type';
import { RepoHeader } from '~/components/RepoHeader';
import { RepoAbout } from '~/components/RepoAbout';
import { BranchNavigation } from '~/components/BranchNavigation';
import { RepoReadMe } from '~/components/RepoReadMe';
import FileExplorer from '~/components/FileExplorer';

const Repository = () => {
  const params = useParams();
  const [branch, setBranch] = createSignal(params.branch);
  const [info, setInfo] = createSignal<Info>({
    isPrivate: false,
    visibility: '',
    forkCount: 0,
    description: '',
    homepageUrl: '',
    stargazerCount: 0,
    watcherCount: 0,
    openIssueCount: 0,
    topics: [],
    isOrg: false,
    openPullRequestCount: 0,
  });

  const isOwnerAndNameValid =
    typeof params.owner === 'string' && typeof params.name === 'string';

  const repoInfo = createQuery(
    () => [`repository-info_${params.owner}_${params.name}`],
    () =>
      getRepoInfo(
        isOwnerAndNameValid
          ? { owner: params.owner, name: params.name }
          : { owner: '', name: '' }
      )
  );

  createEffect(() => {
    if (repoInfo.isSuccess && !repoInfo.isLoading && repoInfo.data) {
      setInfo(repoInfo.data.info);
      setBranch(repoInfo.data.branch || params.branch);
    }
  });

  return (
    <div class="bg-white h-screen">
      <Switch>
        <Match when={repoInfo.isError}>
          <p>Error</p>
        </Match>
        <Match when={repoInfo.isLoading}>
          <div class="mt-2">
            <LoadingPulseDot />
          </div>
        </Match>
        <Match when={repoInfo.isSuccess && !repoInfo.isLoading}>
          <RepoHeader {...info()} />
          <div class="max-w-screen-2xl mx-auto md:py-8 px-4">
            <div class="grid grid-cols-12 gap-8">
              <div class="col-span-12 md:col-span-7 xl:col-span-9">
                <BranchNavigation branch={branch()} />
                <FileExplorer
                  branch={branch()}
                  owner={params.owner}
                  name={params.name}
                />
                <RepoReadMe />
              </div>
              <div class="col-span-12 md:col-span-5 xl:col-span-3">
                <RepoAbout
                  description={info().description}
                  homepageUrl={info().homepageUrl}
                  topics={info().topics || []}
                />
              </div>
            </div>
          </div>
        </Match>
      </Switch>
    </div>
  );
};

export default Repository;

// qwik-graphql-tailwind/src/routes/[owner]/[name]/index.tsx
import { component$, useClientEffect$, useContextProvider, useStore, createContext } from '@builder.io/qwik';
import { useLocation } from '@builder.io/qwik-city';
import { useQuery } from '~/utils/useQuery';
import { GITHUB_GRAPHQL, SPECIAL_PERIOD_CHAR_URL_ENCODED_REGEX } from '~/utils/constants';
import { REPO_INFO_QUERY } from '~/utils/queries/repo-info';
import { parseTopics } from './parseTopics';
import { RepoTree } from '~/components/repo-tree';
import { RepoReadMe } from '~/components/repo-read-me';
import { RepoAboutWidget } from '~/components/repo-about';
import { ISSUES_QUERY } from '~/utils/queries/issues-query';
import { RepoHeader } from '~/components/repo-header';
import { BranchNavigation } from '~/components/branch-navigation';

export interface SharedState {
  name: string;
  owner: string;
  branch?: string;
  path?: string;
  info: {
    error?: string;
    data?: {
      isPrivate: boolean;
      stargazerCount: number;
      forkCount: number;
      watcherCount: number;
      openIssueCount: number;
      openPullRequestCount: number;
      description?: string | null;
      homepageUrl?: string | null;
      topics: string[];
      isOrg: boolean;
    };
    isLoading: boolean;
  };
  tree: {
    error?: string;
    data?: {
      branches: { name: string }[];
      tree: { name: string; type: string; path: string }[];
    };
    isLoading: boolean;
  };
  readme: {
    error?: string;
    text?: any;
    isLoading: boolean;
  };
}

interface IssuesQueryParams {
  owner: string;
  name: string;
  first: number;
}

export const RepoContext = createContext<SharedState>('repo-context');

export default component$(() => {
  const store = useStore<SharedState>(
    {
      owner: '',
      name: '',
      info: {
        isLoading: true,
      },
      tree: {
        isLoading: true,
      },
      readme: {
        isLoading: true,
      },
    },
    { recursive: true }
  );

  const { params } = useLocation();

  const isOwnerAndNameValid = typeof params.owner === 'string' && typeof params.name === 'string';
  const defaultBranch = typeof params.branch === 'string' ? params.branch : 'HEAD';

  useClientEffect$(async () => {
    store.owner = params.owner;
    store.name = params.name.replace(SPECIAL_PERIOD_CHAR_URL_ENCODED_REGEX, '.');
    store.branch = defaultBranch;
    store.path = params.path || '';
    const abortController = new AbortController();
    const response = await fetchRepoInfo(
      isOwnerAndNameValid
        ? {
            owner: params.owner,
            name: params.name,
          }
        : {
            owner: '',
            name: '',
          },
      abortController
    );

    updateRepoInfo(store, response);
  });

  if (store.info.isLoading && store.tree.isLoading) {
    return <div>Loading...</div>;
  }

  useContextProvider(RepoContext, store);

  return (
    <div class="bg-white">
      <RepoHeader
        name={store.name}
        owner={store.owner}
        forkCount={store.info.data?.forkCount || 0}
        watcherCount={store.info.data?.watcherCount || 0}
        stargazerCount={store.info.data?.stargazerCount || 0}
      />
      <div className="max-w-screen-2xl mx-auto md:py-8 px-4">
        <div className="grid grid-cols-12 gap-8">
          <div className="col-span-12 md:col-span-7 xl:col-span-9">
            <BranchNavigation name={store.name} owner={store.owner} path={store.path || ''} branch={store.branch} />
            <RepoTree />
            <RepoReadMe />
          </div>
          <div className="col-span-12 md:col-span-5 xl:col-span-3">
            <RepoAboutWidget />
          </div>
        </div>
      </div>
    </div>
  );
});

export function updateRepoInfo(store: SharedState, response: any) {
  const {
    data: { repository },
  } = response;
  if (repository) {
    store.info.data = {
      isPrivate: repository.isPrivate,
      forkCount: repository.forkCount,
      description: repository.description,
      homepageUrl: repository.homepageUrl,
      stargazerCount: repository.stargazerCount,
      watcherCount: repository.watchers.totalCount,
      openIssueCount: repository.issues.totalCount,
      topics: parseTopics(repository.topics?.nodes),
      isOrg: typeof repository.owner?.orgName === 'string',
      openPullRequestCount: repository.pullRequests.totalCount,
    };
    store.branch = repository?.defaultBranchRef?.name ?? store.branch;
  } else {
    store.info.data = undefined;
    store.info.error = 'No repository found';
  }
  store.info.isLoading = false;
}

export async function fetchRepoInfo(
  variables: {
    owner: string;
    name: string;
  },
  abortController?: AbortController
): Promise<any> {
  const { executeQuery$ } = useQuery(REPO_INFO_QUERY);

  const resp = await executeQuery$({
    signal: abortController?.signal,
    url: GITHUB_GRAPHQL,
    headersOpt: {
      Accept: 'application/vnd.github+json',
      authorization: `Bearer ${sessionStorage.getItem('token')}`,
    },
    variables,
  });

  return await resp.json();
}

export async function fetchIssues(
  { owner, name, first }: IssuesQueryParams,
  abortController?: AbortController
): Promise<any> {
  const { executeQuery$ } = useQuery(ISSUES_QUERY);

  const resp = await executeQuery$({
    signal: abortController?.signal,
    url: GITHUB_GRAPHQL,
    variables: {
      owner,
      name,
      first,
    },
    headersOpt: {
      Accept: 'application/vnd.github+json',
      authorization: `Bearer ${sessionStorage.getItem('token')}`,
    },
  });

  return await resp.json();
}
