// angular-apollo-tailwind/src/app/profile/components/file-text/file-text.component.ts
import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-file-text',
  template: `<pre data-testid="text-block" class="codeBlock">
  <div *ngFor="let line of lines let i = index" class="table-row">
    <span class="lineNumber">{{i + 1}}</span>
    <span class="table-cell">{{line}}</span>
  </div>
</pre>`,
  styleUrls: ['./file-text.component.css'],
})
export class FileTextComponent {
  @Input() set text(val: string) {
    this.lines = val.split('\n');
  }

  lines: string[] = [];
}

// next-react-query-tailwind/src/components/FileViewer/FileText.tsx
import styles from './FileViewer.module.css';

interface FileTextProps {
  text: string;
}

function FileText({ text }: FileTextProps) {
  const lines = text.split('\n');
  return (
    <pre data-testid="text-block" className={styles.codeBlock}>
      {lines.map((line, i) => (
        <div key={i} className="table-row">
          <span className={styles.lineNumber}>{i + 1}</span>
          <span className="table-cell">{line}</span>
        </div>
      ))}
    </pre>
  );
}

export default FileText;
