// solidjs-tailwind/src/components/FileViewer/FileText.jsx
import { For } from 'solid-js';
import styles from './FileViewer.module.css';

const FileCode = (props) => {
  return (
    <pre data-testid="text-block" class={styles.codeBlock}>
      <For each={props.text?.split('\n')}>
        {(line, i) => (
          <div class="table-row">
            <span class={styles.lineNumber}>{i() + 1}</span>
            <span class="table-cell">{line}</span>
          </div>
        )}
      </For>
    </pre>
  );
};

export default FileCode;

// next-react-query-tailwind/src/components/FileViewer/FileText.tsx
import styles from './FileViewer.module.css';

interface FileTextProps {
  text: string;
}

function FileText({ text }: FileTextProps) {
  const lines = text.split('\n');
  return (
    <pre data-testid="text-block" className={styles.codeBlock}>
      {lines.map((line, i) => (
        <div key={i} className="table-row">
          <span className={styles.lineNumber}>{i + 1}</span>
          <span className="table-cell">{line}</span>
        </div>
      ))}
    </pre>
  );
}

export default FileText;
