// remix/app/components/Pagination/Pagination.tsx
import cn from 'classnames';
import { useNavigate } from 'react-router-dom';
import * as styles from './Pagination.classNames';

interface PaginationProps {
  pageInfo?: any;
  owner: string;
}

function Pagination({ pageInfo, owner }: PaginationProps) {
  if (!pageInfo) {
    return null;
  }

  const prevUrl = `/${owner}?before=${pageInfo.startCursor}`;
  const nextUrl = `/${owner}?after=${pageInfo.endCursor}`;
  let navigate = useNavigate();

  const handlePreviousClick = () => {
    navigate(prevUrl);
  };

  const handleNextClick = () => {
    navigate(nextUrl);
  };

  return (
    <div className={styles.container}>
      <span className={styles.group}>
        <button
          type="button"
          disabled={!pageInfo.hasPreviousPage || !pageInfo.startCursor}
          onClick={handlePreviousClick}
          className={cn(styles.button, styles.buttonPrev)}
        >
          Previous
        </button>
        <button
          type="button"
          onClick={handleNextClick}
          disabled={!pageInfo.hasNextPage || !pageInfo.endCursor}
          className={cn(styles.button, styles.buttonNext)}
        >
          Next
        </button>
      </span>
    </div>
  );
}

export default Pagination;

// solidstart-tanstackquery-tailwind-modules/src/components/Pagination/Pagination.tsx
import { useNavigate } from '@solidjs/router';
import { Show } from 'solid-js';
import { PageInfo } from '~/types/user-repo-type';
import styles from './Pagination.module.css';

interface IProps {
  pageInfo: PageInfo;
  owner: string;
  tab?: string;
}

const Pagination = (props: IProps) => {
  const navigate = useNavigate();

  const handlePreviousClick = () =>
    navigate(
      `/${props.owner}?before=${props.pageInfo.startCursor}${
        props.tab ? `&tab=${props.tab}` : ''
      }`
    );

  const handleNextClick = () =>
    navigate(
      `/${props.owner}?after=${props.pageInfo.endCursor}${
        props.tab ? `&tab=${props.tab}` : ''
      }`
    );

  return (
    <Show when={props.pageInfo}>
      <div class={styles.container}>
        <span class={styles.wrapper}>
          <button
            type="button"
            disabled={
              !props.pageInfo.hasPreviousPage || !props.pageInfo.startCursor
            }
            onClick={handlePreviousClick}
            class={styles.btn_container + ' rounded-l-lg'}
          >
            Previous
          </button>
          <button
            type="button"
            onClick={handleNextClick}
            disabled={!props.pageInfo.hasNextPage || !props.pageInfo.endCursor}
            class={styles.btn_container + ' rounded-r-lg'}
          >
            Next
          </button>
        </span>
      </div>
    </Show>
  );
};

export default Pagination;
