// solidjs-tailwind/src/components/RepoFilter/FilterDropdown.jsx
import {
  createSignal,
  Show,
  splitProps,
  For,
  Switch,
  Match,
} from 'solid-js';
import { CaretIcon, CloseIcon, CorrectIcon } from '../Icons';
import { clickOutside } from '../../utils/onclick-outside';

const FilterDropdown = (props) => {
  const [local] = splitProps(props, ['name', 'title', 'items', 'selected', 'selectOption']);
  const [showOptions, setShowOptions] = createSignal(false);
  const toggleOption = () => setShowOptions(!showOptions());

  return (
    <div
      data-testid="filter-dropdown"
      class="relative inline-block text-left"
      use:clickOutside={() => setShowOptions(false)}
    >
      <div>
        <button
          onClick={toggleOption}
          type="button"
          data-testid="filter-dropdown-button"
          class="inline-flex w-full justify-center items-center gap-2 rounded-md border border-gray-300 bg-white px-4 py-1.5 text-sm font-medium text-gray-700 shadow-sm hover:bg-gray-50 focus:outline-none"
          id="menu-button"
          aria-expanded="true"
          aria-haspopup="true"
        >
          {local.name}
          <CaretIcon />
        </button>
      </div>
      <Show when={showOptions()}>
        <div
          class="absolute right-0 z-10 mt-2 w-56 origin-top-right divide-y divide-gray-100 rounded-md bg-white shadow-lg ring-1 ring-black ring-opacity-5 focus:outline-none"
          role="menu"
          aria-orientation="vertical"
          aria-labelledby="menu-button"
          tabindex="-1"
        >
          <div class="flex justify-between items-center text-sm text-gray-600 px-3 py-1">
            <strong class="capitalize text-xs">Select {local.name}</strong>
            <button onClick={() => setShowOptions(false)}>
              <CloseIcon />
            </button>
          </div>
          <For each={local.items}>
            {(item, index) => (
              <div
                data-index={index()}
                class="py-1 transition delay-[50ms] hover:bg-gray-300 cursor-pointer"
                role="none"
                onClick={() => local.selectOption(item)}
              >
                <span
                  class="text-gray-700 px-4 py-2 text-sm flex items-center gap-3"
                  role="menuitem"
                  tabindex="-1"
                >
                  <Switch fallback={<span class="mr-4" />}>
                    <Match when={item === local.selected}>
                      <CorrectIcon />
                    </Match>
                  </Switch>
                  {item}
                </span>
              </div>
            )}
          </For>
        </div>
      </Show>
    </div>
  );
};

export default FilterDropdown;

// next-react-query/src/components/RepoFilters/FilterDropdown.tsx
import cn from 'classnames';
import { Fragment } from 'react';
import { Menu, Transition } from '@headlessui/react';
import { ChevronDownIcon, XIcon, CheckIcon } from '@heroicons/react/solid';

interface Option {
  label: string;
  value: number | string;
}

interface DropdownProps {
  name: string;
  description?: string;
  current: number | string;
  items: Option[];
  onChange: (value: any) => void;
}

function Dropdown({
  name,
  description,
  current,
  items,
  onChange,
}: DropdownProps) {
  return (
    <Menu as="div" className="relative inline-block text-left z-30">
      <div>
        <Menu.Button className="relative inline-flex items-center px-4 py-1.5 rounded-md bg-gray-100 bg-opacity-75 border border-gray-300 text-sm font-medium text-gray-800 hover:bg-gray-200 hover:bg-opacity-50">
          {name}
          <ChevronDownIcon
            className="-mr-1 ml-1 mt-0.5 h-4 w-4"
            aria-hidden="true"
          />
        </Menu.Button>
      </div>

      <Transition
        as={Fragment}
        enter="transition ease-out duration-100"
        enterFrom="transform opacity-0 scale-95"
        enterTo="transform opacity-100 scale-100"
        leave="transition ease-in duration-75"
        leaveFrom="transform opacity-100 scale-100"
        leaveTo="transform opacity-0 scale-95"
      >
        <Menu.Items className="origin-top-right absolute right-0 mt-2 w-72 rounded-md shadow-lg bg-white ring-1 ring-black ring-opacity-5 focus:outline-none">
          <div>
            {description && (
              <div className="flex justify-between items-center">
                <div className="px-4 py-2.5 text-xs text-gray-800 font-semibold">
                  {description}
                </div>
                <Menu.Button>
                  <XIcon
                    className="mr-2 h-4 w-4 text-gray-600"
                    aria-hidden="true"
                  />
                </Menu.Button>
              </div>
            )}
            {items.map(({ label, value }) => (
              <Menu.Item key={value}>
                <button
                  type="button"
                  className="relative w-full text-left text-xs py-2 px-10 border-t border-gray-300 hover:bg-gray-100 capitalize"
                  onClick={() => {
                    onChange(value);
                  }}
                >
                  {value === current && (
                    <CheckIcon className="inline w-4 h-4 absolute left-4" />
                  )}{' '}
                  {label}
                </button>
              </Menu.Item>
            ))}
          </div>
        </Menu.Items>
      </Transition>
    </Menu>
  );
}

export default Dropdown;
