// svelte-kit-scss/src/lib/components/shared/FilterDropdown/FilterDropdown.svelte
<script lang="ts">
  import { clickOutside } from '../actions/clickOutside';
  import type { FilterDropdownOption } from './filter-option';
  import { createEventDispatcher } from 'svelte';
  import { scale } from 'svelte/transition';
  import { Check16, ChevronDown16, X16 } from 'svelte-octicons';

  export let name = '';

  export let description = 'Select option';

  export let defaultFilter: FilterDropdownOption | undefined = undefined;

  export let items: FilterDropdownOption[] = [];

  export let borderNone = false;

  export let current: FilterDropdownOption | undefined = defaultFilter;

  let isOpen = false;

  const toggleMenu = (): void => {
    isOpen = !isOpen;
  };

  const closeDropdown = (): void => {
    isOpen = false;
  };

  const dispatch = createEventDispatcher();

  const dispatchSetFilter = () => {
    dispatch('setFilter', current);
  };

  const handleFilterOptionClick = (item: FilterDropdownOption): void => {
    current = item;
    dispatchSetFilter();
    closeDropdown();
  };
</script>

<div class="filter-dropdown-container" use:clickOutside on:clickoutside={closeDropdown}>
  <button class="button" class:border-none={borderNone} on:click={toggleMenu}>
    {name}
    <ChevronDown16 />
  </button>
  {#if isOpen}
    <div
      class="menu"
      data-testid="filterDropdown"
      transition:scale={{ duration: 100, start: 0.95 }}
    >
      <div class="header">
        <div class="description">{description}</div>
        <div class="close" on:click={closeDropdown} on:keypress={closeDropdown}>
          <span class:invisible={current?.value === defaultFilter}>
            <X16 />
          </span>
        </div>
      </div>

      <ul class="items">
        {#each items as item}
          <li
            class="item noselect"
            on:click={() => handleFilterOptionClick(item)}
            on:keypress={() => handleFilterOptionClick(item)}
          >
            <span class="icon" class:invisible={item !== current}>
              <Check16 />
            </span>
            <span>{item.label}</span>
          </li>
        {/each}
      </ul>
    </div>
  {/if}
</div>

<style lang="scss">
  @use 'src/lib/styles/variables.scss';

  .filter-dropdown-container {
    position: relative;
    display: inline-block;
    font-size: 16px;
    .button {
      padding: 0.375em 1em;
      line-height: 1.5em;
      font-size: 0.875em;
      font-weight: 500;
      border-radius: 0.375em;
      border: 1px solid variables.$gray300;
      background-color: variables.$gray100;

      &.border-none {
        border: 0px;
        background: none;
      }
    }
    .menu {
      position: absolute;
      right: 0;
      margin-top: 0.5em;
      background-color: variables.$white;
      transform-origin: top right;
      width: 18em;
      border-radius: 0.375em;
      border: 1px solid variables.$gray300;
      box-shadow: 0 1px 2px 0 rgba(variables.$black, 0.05);
      .header {
        display: flex;
        padding: 0.625em 1em;
        font-size: 0.75em;
        line-height: 1em;
        font-weight: 600;
        .description {
          flex-grow: 1;
        }
        .close {
          cursor: pointer;
        }
      }
      ul.items {
        padding: 0;
        margin: 0;
        list-style-type: none;
        .item {
          padding: 0.5em 1em;
          text-align: left;
          font-size: 0.75em;
          line-height: 1.25em;
          text-transform: capitalize;
          border-top: 1px solid variables.$gray300;
          &:hover {
            background-color: variables.$gray100;
          }
          .icon {
            margin-right: 0.25em;
          }
        }
      }
    }
  }
</style>

// next-react-query/src/components/RepoFilters/FilterDropdown.tsx
import cn from 'classnames';
import { Fragment } from 'react';
import { Menu, Transition } from '@headlessui/react';
import { ChevronDownIcon, XIcon, CheckIcon } from '@heroicons/react/solid';

interface Option {
  label: string;
  value: number | string;
}

interface DropdownProps {
  name: string;
  description?: string;
  current: number | string;
  items: Option[];
  onChange: (value: any) => void;
}

function Dropdown({
  name,
  description,
  current,
  items,
  onChange,
}: DropdownProps) {
  return (
    <Menu as="div" className="relative inline-block text-left z-30">
      <div>
        <Menu.Button className="relative inline-flex items-center px-4 py-1.5 rounded-md bg-gray-100 bg-opacity-75 border border-gray-300 text-sm font-medium text-gray-800 hover:bg-gray-200 hover:bg-opacity-50">
          {name}
          <ChevronDownIcon
            className="-mr-1 ml-1 mt-0.5 h-4 w-4"
            aria-hidden="true"
          />
        </Menu.Button>
      </div>

      <Transition
        as={Fragment}
        enter="transition ease-out duration-100"
        enterFrom="transform opacity-0 scale-95"
        enterTo="transform opacity-100 scale-100"
        leave="transition ease-in duration-75"
        leaveFrom="transform opacity-100 scale-100"
        leaveTo="transform opacity-0 scale-95"
      >
        <Menu.Items className="origin-top-right absolute right-0 mt-2 w-72 rounded-md shadow-lg bg-white ring-1 ring-black ring-opacity-5 focus:outline-none">
          <div>
            {description && (
              <div className="flex justify-between items-center">
                <div className="px-4 py-2.5 text-xs text-gray-800 font-semibold">
                  {description}
                </div>
                <Menu.Button>
                  <XIcon
                    className="mr-2 h-4 w-4 text-gray-600"
                    aria-hidden="true"
                  />
                </Menu.Button>
              </div>
            )}
            {items.map(({ label, value }) => (
              <Menu.Item key={value}>
                <button
                  type="button"
                  className="relative w-full text-left text-xs py-2 px-10 border-t border-gray-300 hover:bg-gray-100 capitalize"
                  onClick={() => {
                    onChange(value);
                  }}
                >
                  {value === current && (
                    <CheckIcon className="inline w-4 h-4 absolute left-4" />
                  )}{' '}
                  {label}
                </button>
              </Menu.Item>
            ))}
          </div>
        </Menu.Items>
      </Transition>
    </Menu>
  );
}

export default Dropdown;
