// qwik-graphql-tailwind/src/components/user-profile-card/user-profile-card.tsx
import { component$ } from '@builder.io/qwik';
import { BuildingIcon, LinkIcon, LocationMarkerIcon, StarIcon, TwitterIcon, UsersIcon } from '../icons';
import { OrgList } from '../org-list/org-list';
import { User } from '../../utils/types';
import * as styles from './user-profile-card.classNames';

export const UserProfileCard = component$(
  ({
    avatarUrl,
    bio,
    company,
    location,
    login,
    name,
    twitterUsername,
    websiteUrl,
    followers,
    following,
    starredRepositories,
    organizations,
  }: User) => {
    return (
      <div>
        <img src={avatarUrl} alt="Avatar" width={260} height={260} className={styles.avatar} />
        <h1 className="mt-2">
          <div className={styles.name}>{name}</div>
          <div className={styles.username}>{login}</div>
        </h1>
        {bio && <div className={styles.bio} dangerouslySetInnerHTML={bio} />}
        <div className={styles.socials}>
          <UsersIcon className={styles.icon} />
          <span className="inline-block">
            <span className={styles.count}>{followers.totalCount}</span> followers
          </span>
          <span className="mx-1">·</span>
          <span className="inline-block">
            <span className={styles.count}>{following.totalCount}</span> following
          </span>
          <span className="mx-1">·</span>
          <StarIcon className={styles.icon} />
          <span className="inline-block">
            <span className={styles.count}>{starredRepositories.totalCount}</span>{' '}
          </span>
        </div>
        <div className={styles.fields}>
          {company && (
            <div>
              <BuildingIcon className={styles.icon} />
              {company}
            </div>
          )}
          {location && (
            <div>
              <LocationMarkerIcon className={styles.icon} />
              {location}
            </div>
          )}
          {websiteUrl && (
            <div>
              <LinkIcon className={styles.icon} />
              <a className={styles.link} href={`https://${websiteUrl}`} target="_blank" rel="noreferrer">
                {websiteUrl}
              </a>
            </div>
          )}
          {twitterUsername && (
            <div>
              <TwitterIcon className={styles.icon} />
              <a
                className={styles.link}
                href={`https://twitter.com/${twitterUsername}`}
                target="_blank"
                rel="noreferrer"
              >
                @{twitterUsername}
              </a>
            </div>
          )}
        </div>
        {organizations.nodes.length > 0 && <OrgList organizations={organizations.nodes} />}
      </div>
    );
  }
);

// vue3-apollo-quasar/src/components/UserProfileCard/UserProfileCard.vue
<template>
  <!-- Actual content -->
  <q-card
    v-if="!userLoading"
    class="full-height"
    flat
    square
    style="width: 325px"
  >
    <q-card-section class="" v-bind="$attrs">
      <q-list>
        <q-item-section>
          <q-avatar class="" type="circle" style="width: 18rem; height: 18rem">
            <img :src="userData?.avatarUrl" alt="avatar" />
          </q-avatar>
        </q-item-section>
      </q-list>
      <q-list>
        <q-item-section>
          <q-item-label
            class="name text-bold q-pt-md"
            style="font-size: 24px; line-height: 1.25"
          >
            {{ userData?.name }}
          </q-item-label>
          <q-item-label
            class="login"
            style="
              font-size: 20px;
              line-height: 24px;
              color: var(--color-fg-muted);
            "
          >
            {{ userData?.login }}
          </q-item-label>
        </q-item-section>
      </q-list>
      <q-list>
        <!-- bio section -->
        <q-item-section class="bio">
          {{ userData?.bio }}
        </q-item-section>
        <!-- follow section TODO: spacing issues and alignment-->
        <q-item-section style="display: inline">
          <q-item-label>
            <a
              href="#"
              style="text-decoration: none"
              v-if="userData?.followers?.totalCount"
            >
              <q-icon
                class="q-mr-xs"
                style="color: var(--color-btn-text)"
                name="fas fa-users"
              ></q-icon>
              <span
                class="text-bold q-pl-sm q-pr-sm"
                style="color: var(--color-btn-text)"
              >
                {{ userData?.followers?.totalCount }}</span
              >
              <span style="color: var(--color-fg-muted)">followers</span>
            </a>
            ·
            <a
              href="#"
              style="text-decoration: none"
              v-if="userData?.following?.totalCount"
            >
              <span
                class="text-bold q-pr-sm"
                style="color: var(--color-btn-text)"
                >{{ userData?.following?.totalCount }}</span
              >
              <span style="color: var(--color-fg-muted)">following</span>
            </a>
            ·
            <a
              href="#"
              style="text-decoration: none"
              v-if="userData?.followers?.totalCount"
            >
              <q-icon
                class="q-mr-xs"
                style="color: var(--color-btn-text)"
                name="far fa-star"
              ></q-icon>
              <span
                class="text-bold q-pl-sm"
                style="color: var(--color-btn-text)"
              >
                {{
                  userData?.starredRepositories?.totalCount?.toLocaleString() ||
                  0
                }}
              </span>
            </a>
          </q-item-label>
        </q-item-section>
      </q-list>
      <!-- media section -->
      <q-list style="margin-top: 1rem">
        <q-item-section>
          <q-item-label
            v-if="userData?.company"
            class="items-center text-bold"
            style="margin-bottom: 4px"
          >
            <q-icon class="q-mr-xs" name="far fa-building"></q-icon>
            {{ userData?.company }}</q-item-label
          >
          <q-item-label
            v-if="userData?.location"
            class="items-center"
            style="margin-bottom: 4px"
          >
            <q-icon class="q-mr-xs" name="fas fa-map-marker-alt"></q-icon>
            {{ userData?.location }}</q-item-label
          >
          <q-item-label
            v-if="userData?.websiteUrl"
            class="items-center"
            style="margin-bottom: 4px"
          >
            <q-icon class="q-mr-xs" name="fas fa-link"></q-icon>
            <a
              :href="userData?.websiteUrl"
              target="__blank"
              style="
                text-decoration: none;
                margin-left: 4px;
                color: var(--color-btn-text);
              "
              >{{ userData?.websiteUrl }}</a
            >
          </q-item-label>
          <q-item-label
            v-if="userData?.twitterUsername"
            class="items-center"
            style="margin-bottom: 1rem"
          >
            <q-icon class="q-mr-xs" name="fab fa-twitter"></q-icon>
            <a
              href="https://twitter.com/${userData.twitterUsername}"
              target="__blank"
              style="
                text-decoration: none;
                margin-left: 4px;
                color: var(--color-btn-text);
              "
              >@{{ userData?.twitterUsername }}</a
            >
          </q-item-label>
        </q-item-section>
      </q-list>
      <!-- org section -->
      <template late v-if="userData?.organizations?.nodes?.length">
        <q-separator></q-separator>
        <q-list>
          <q-item-section>
            <p-item-label class="text-bold q-pt-md" style="font-size: 16px">
              Organizations
            </p-item-label>
            <a
              v-for="organization in userData?.organizations?.nodes"
              :href="organization?.login"
              :key="`org-${organization?.login}`"
              class="q-pt-sm"
            >
              <img
                :src="organization?.avatarUrl"
                alt="some"
                class="avatar"
                style="width: 32px; height: 32px"
              />
            </a>
          </q-item-section>
        </q-list>
      </template>
    </q-card-section>
  </q-card>
  <!-- Loading -->
  <div v-else class="q-mt-md q-px-lg" style="width: 325px">
    <div class="full-width text-center q-mb-md">
      <q-skeleton
        class="avatar q-mb-sm"
        type="circle"
        style="width: 18rem; height: 18rem"
      ></q-skeleton>
    </div>
    <q-skeleton class="q-mb-xs" type="rect"></q-skeleton>
    <q-skeleton class="q-mb-md" type="text"></q-skeleton>

    <div class="row q-col-gutter-x-md q-mb-lg">
      <div class="col-6">
        <q-skeleton type="rect"></q-skeleton>
      </div>
      <div class="col-6">
        <q-skeleton type="rect"></q-skeleton>
      </div>
    </div>
    <q-skeleton class="q-mb-md" type="text"></q-skeleton>
    <q-skeleton class="q-mb-md" type="text"></q-skeleton>
  </div>
</template>

<script lang="ts">
import { defineComponent, defineProps } from 'vue';

export default defineComponent({
  name: 'UserProfileCard',
});
</script>

<script lang="ts" setup>
import { useUser } from '@/composables';

const { getUserProfile } = useUser();
const props = defineProps({
  username: String,
});
const { data: userData, loading: userLoading } = getUserProfile(props.username);
</script>

<style lang="scss" scoped>
@import '../../App.css';
</style>
