// expo-zustand-styled-components/src/screens/Repository/Issues/Issues.tsx
import React, { useEffect } from 'react';
import { View, Text } from 'react-native';
import { useRoute } from '@react-navigation/native';
import { parseSortParams } from '../../../utils/parseSortParams';
import { useIssuesStore, usePRAndIssueHeaderStore } from '../../../hooks/stores';
import { DEFAULT_PAGE_SIZE, SORT_OPTIONS } from '../../../utils/constants';
import getIssues from '../../../services/get-repo-issues';

interface UseRoute {
  params?: {
    name?: string;
    owner?: string;
  };
}
const Issues = () => {
  const { params }:UseRoute = useRoute();
  const {after, before, isLoading, issues} = useIssuesStore();
  const { sortBy, label, milestone } = usePRAndIssueHeaderStore();
  
  // const params = usePara
  const fetchParameters = () => ({
    owner: params.owner,
    name: params.name,
    orderBy: parseSortParams(SORT_OPTIONS, sortBy, 0),
    direction: parseSortParams(SORT_OPTIONS, sortBy, 1),
    filterBy: {
      labels: label ? [label] : undefined,
      milestone: milestone ? milestone : undefined,
    },
    before: typeof before === 'string' ? before : undefined,
    after: typeof after === 'string' ? after : undefined,
    first: after || !before ? DEFAULT_PAGE_SIZE : undefined,
    last: before ? DEFAULT_PAGE_SIZE : undefined,
  });

  useEffect(() => {
    if(!isLoading) {
      console.log('====================================');
      console.log(issues);
      console.log('====================================');
    }
  },[isLoading])

  useEffect(() => {
    getIssues(fetchParameters());
  },[before, after, sortBy, milestone, label])
  return (
    <View>
      <Text>{isLoading ? 'Loading...': 'Done'}</Text>
      <Text>Issues</Text>
    </View>
  );
};

export default Issues;

// vue3-apollo-quasar/src/views/Repository/Issues/Issues.vue
<template>
  <IssuesWrapper :issueData="issueData" />
</template>

<script lang="ts">
import { useIssue } from '@/composables';
import { defineComponent, defineProps, watch, ref } from 'vue';
import { IssueResp } from '@/composables/github/types';

export default defineComponent({
  name: 'Issues',
});
</script>

<script lang="ts" setup>
import IssuesWrapper from './IssuesWrapper.vue';
import { DEFAULT_PAGE_SIZE, parseSortParams, SORT_OPTIONS } from '@/helpers';
import { useRepoStore } from '@/store/respoStore';
import { useRoute } from 'vue-router';

const props = defineProps({
  owner: {
    type: String,
    default: '',
  },
  repo: {
    type: String,
    default: '',
  },
});

const repoStore = useRepoStore();

const {
  query,
}: {
  query: {
    before?: string;
    after?: string;
  };
} = useRoute();
const issueData = ref<{ value: IssueResp }>();
const { getIssues } = useIssue();

watch(
  [
    () => repoStore.selectedLabel,
    () => repoStore.milestoneNumber,
    () => repoStore.sortBy,
    () => props.owner,
    () => props.repo,
    () => query.before,
    () => query.after,
  ],
  () => {
    repoStore.setLoading(ref(true));
    const { data: issueDatax, loading } = getIssues({
      owner: props.owner,
      name: props.repo,
      orderBy: parseSortParams(SORT_OPTIONS, repoStore.sortBy, 0),
      direction: parseSortParams(SORT_OPTIONS, repoStore.sortBy, 1),
      filterBy: {
        labels: repoStore.selectedLabel ? [repoStore.selectedLabel] : undefined,
        milestoneNumber: repoStore.milestoneNumber,
      },
      before: query.before,
      after: query.after,
      first: query.after || !query.before ? DEFAULT_PAGE_SIZE : undefined,
      last: query.before ? DEFAULT_PAGE_SIZE : undefined,
    });
    repoStore.setLoading(loading);
    issueData.value = issueDatax;
  },
  {
    immediate: true,
  },
);
</script>

<style lang="scss" scoped>
.issues-section {
  max-width: 70rem;
}
</style>
