// angular-apollo-tailwind/src/app/profile/org-profile/org-profile.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-org-profile',
  templateUrl: './org-profile.component.html',
})
export class OrgProfileComponent {}

<div
  class="border-b border-gray-200 sticky top-0 bg-white hidden md:block z-50"
>
  <div class="grid grid-cols-12 max-w-screen-lg mx-auto">
    <div class="col-span-12 md:col-span-8 xl:col-span-12 px-4">
      <app-org-profile-about [profile]="profile"></app-org-profile-about>
    </div>
    <div class="col-span-12 md:col-span-8 xl:col-span-12">
      <app-profile-nav class="border-none"></app-profile-nav>
    </div>
  </div>
</div>

<div class="max-w-screen-lg mx-auto py-8 px-4">
  <div class="grid grid-cols-12 gap-8">
    <div class="col-span-12 md:col-span-8 xl:col-span-12">
      <app-profile-nav class="border-none md:hidden"></app-profile-nav>
      <router-outlet></router-outlet>
    </div>
  </div>
</div>

// solidjs-tailwind/src/pages/OrgProfile.jsx
import { For } from 'solid-js';
import { RepoCard, OrgAbout, RepoFilter } from '../components';
import { repoCardProps } from '../components/RepoCard/data';

const OrgProfile = () => {
  return (
    <div class="relative pt-4">
      <div class="border-b border-gray-200 sticky top-0 bg-white hidden md:block z-50">
        <div class="grid grid-cols-12 max-w-screen-lg mx-auto">
          <div class="col-span-12 md:col-span-8 xl:col-span-12 px-4">
            <OrgAbout />
          </div>
          <div class="col-span-12 md:col-span-8 xl:col-span-12">
            {/* TODO:  <ProfileNav /> goes here with class="border-none */}
          </div>
        </div>
      </div>
      <div class="max-w-screen-lg mx-auto py-8 px-4">
        <div class="grid grid-cols-12 gap-8">
          <div class="col-span-12 md:col-span-8 xl:col-span-12">
            {/* TODO:  <ProfileNav /> goes here with class="border-none md:hidden" */}
            <RepoFilter />
            {/* TODO: replace repoCardProps with real data */}
            <For each={[repoCardProps]}>
              {(props) => <RepoCard {...props} isProfilePage />}
            </For>
          </div>
        </div>
      </div>
    </div>
  );
};

export default OrgProfile;
