// solidstart-tanstackquery-tailwind-modules/src/components/TabNavigation/TabNavigation.tsx
import { NavLink } from '@solidjs/router';
import { For, Show } from 'solid-js';
import cn from 'classnames';
import styles from './TabNavigation.module.css';

type Tabs = {
  path: string;
  title: string;
  count: number;
  Icon: Element;
};

type TabNavigationProps = {
  pathname: string;
  class: string;
  tabs: () => Tabs[];
  basePath: string;
};

const TabNavigation = (props: TabNavigationProps) => {
  const isCurrentTab = (pathName: string) => {
    const otherPaths = props.tabs
      //@ts-ignore
      .filter(({ path }: { path: string }) => path !== pathName)
      .map(({ path }: { path: string }) => path);
    return pathName !== ''
      ? props.pathname.includes(pathName)
      : otherPaths.every((path: string) => !props.pathname.includes(path));
  };

  return (
    <div class={`${styles.container} ${props.class}`}>
      <nav class={styles.nav} aria-label="Tabs">
        <For
          //@ts-ignore
          each={props.tabs}
          fallback={<div>Loading...</div>}
        >
          {(item, index) => {
            const href =
              item.path === ''
                ? `/${props.basePath}`
                : `/${props.basePath}/${item.path}`;
            return (
              <NavLink
                href={href}
                //@ts-ignore
                key={index}
                class={`${
                  isCurrentTab(item.path)
                    ? styles.tabActive
                    : styles.tabInactive
                } ${styles.tab}`}
              >
                <item.Icon
                  class={cn(
                    isCurrentTab(item.path)
                      ? styles.iconActive
                      : styles.iconInactive,
                    styles.icon
                  )}
                />
                <span>{item.title}</span>
                <Show when={item.count && item.count > 0}>
                  <span class="ml-2 rounded-xl bg-gray-200 py-0.5 px-2 text-xs font-medium text-gray-800">
                    {item.count}
                  </span>
                </Show>
              </NavLink>
            );
          }}
        </For>
      </nav>
    </div>
  );
};

export default TabNavigation;

// remix-gql-tailwind/app/components/TabNavigation/TabNavigation.tsx
import type { TabItem } from './types';
import cn from 'classnames';
import { Link } from 'remix';
import * as styles from './TabNavigation.classNames';

interface TabNavigationProps {
  tabs: TabItem[];
  basePath?: string;
  className?: string;
  isOrg?: boolean;
  pathname: string;
}

function TabNavigation({
  tabs,
  className,
  basePath = '',
  pathname,
}: TabNavigationProps) {
  const isCurrentTab = (pathName?: string) => {
    const otherPaths = tabs.filter(({ path }) => path !== pathName).map(({ path }) => path);
    return pathName !== '' ? pathname.includes(pathName!) : (otherPaths.every(path => !pathname.includes(path!)))
  };

  return (
    <div className={cn(styles.container, className)}>
      <nav className={styles.nav} aria-label="Tabs">
        {tabs.map(({ title, path, Icon, count }, index) => {
          let href = path === '' ? `/${basePath}` : `/${basePath}/${path}`;
          return (
            <Link
              to={href}
              key={index}
              className={cn(
                isCurrentTab(path) ? styles.tabActive : styles.tabInactive,
                styles.tab
              )}
            >
              <Icon
                className={cn(
                  isCurrentTab(path) ? styles.iconActive : styles.iconInactive,
                  styles.icon
                )}
              />
              <span>{title}</span>
              {typeof count === 'number' && (
                <span className="ml-2 bg-gray-200 font-medium text-xs text-gray-800 py-0.5 px-2 rounded-xl">
                  {count}
                </span>
              )}
            </Link>
          );
        })}
      </nav>
    </div>
  );
}

export default TabNavigation;
