// cra-rxjs-styled-components/src/components/user-repos/UserRepos.tsx
import { Star } from '@styled-icons/heroicons-outline';
import {
  Aside,
  BadgeWrapper,
  Containers,
  Content,
  Description,
  Header,
  HeadingLink,
  RepoListWrapper,
  StarBtn,
  StarIcon,
} from './UserRepos.styles';
import RepoMeta from '../repo-meta';
import PrivacyBadge from '../misc/Privacy-badge';
import { useUserRepositories } from '../../hooks/user-repositories/use-user-repositories';

function UserRepos({ isOrg = false }) {
  const { loading, repos } = useUserRepositories(isOrg);

  if (loading) {
    return <p>Loading...</p>;
  }

  return (
    <RepoListWrapper>
      {repos &&
        repos.map(
          ({
            id,
            name,
            owner,
            description,
            stargazers_count,
            forks_count,
            language,
            updated_at,
            visibility,
          }) => (
            <Containers key={id}>
              <Content>
                <Header>
                  <HeadingLink to={`/${owner.login}/${name}`}>
                    {name}
                  </HeadingLink>
                  <BadgeWrapper>
                    <PrivacyBadge visibility={visibility} />
                  </BadgeWrapper>
                </Header>
                <Description>{description}</Description>
                <RepoMeta
                  language={language}
                  forkCount={forks_count}
                  stargazerCount={stargazers_count}
                  updatedAt={updated_at}
                />
              </Content>
              <Aside>
                <StarBtn>
                  <StarIcon>
                    <Star />
                  </StarIcon>
                  Star
                </StarBtn>
              </Aside>
            </Containers>
          )
        )}
    </RepoListWrapper>
  );
}

export default UserRepos;

// qwik-graphql-tailwind/src/components/user-repos/user-repos.tsx
import { component$ } from '@builder.io/qwik';
import { Link } from '@builder.io/qwik-city';
import { StarIcon } from '../icons';
import { Repo } from './types';
import * as styles from './user-repos.classNames';
import { RepoMeta } from '../repo-meta/repo-meta';
import { PrivacyBadge } from '../privacy-badge/privacy-badge';
import { Pagination } from '../pagination/pagination';

export interface UserReposViewProps {
  repos: Repositories;
  owner: string;
}

export interface Repositories {
  nodes: Repo[];
  pageInfo:
    | {
        __typename?: 'PageInfo' | undefined;
        endCursor?: string | null | undefined;
        startCursor?: string | null | undefined;
        hasNextPage: boolean;
        hasPreviousPage: boolean;
      }
    | undefined;
}

export const UserRepos = component$(({ repos, owner }: UserReposViewProps) => {
  console.log(repos);

  return (
    <>
      {/* <RepoFilters {...repoFilters} languages={languages} resultCount={filteredRepos.length} /> */}
      {repos.nodes.map(
        ({ id, name, description, stargazerCount, forkCount, language, languageColor, updatedAt, isPrivate }) => (
          <div key={id} className={styles.container}>
            <div className={styles.content}>
              <h3 className="mb-2">
                <Link href={`/${owner}/${name}`} className={styles.headingLink}>
                  {name}
                </Link>
                <PrivacyBadge isPrivate={isPrivate} className="relative bottom-0.5" />
              </h3>
              <div className={styles.description}>{description}</div>
              <RepoMeta
                language={language}
                languageColor={languageColor}
                forkCount={forkCount}
                stargazerCount={stargazerCount}
                updatedAt={updatedAt}
              />
            </div>
            <div className={styles.aside}>
              <button className={styles.starBtn}>
                <StarIcon className={styles.starIcon} />
                Star
              </button>
            </div>
          </div>
        )
      )}
      {(repos.pageInfo?.hasNextPage || repos.pageInfo?.hasPreviousPage) && (
        <Pagination pageInfo={repos.pageInfo} owner={owner} />
      )}
    </>
  );
});
