// vite-apollo-vanilla/.storybook/preview.jsx
import { MemoryRouter } from 'react-router-dom';
import '../src/lib/css/base.css';

export const parameters = {
  actions: { argTypesRegex: '^on[A-Z].*' },
  controls: {
    matchers: {
      color: /(background|color)$/i,
      date: /Date$/,
    },
  },
};

export const decorators = [
  (Story) => (
    <MemoryRouter>
      <Story />
    </MemoryRouter>
  ),
];

// solidjs-tailwind/.storybook/preview.js
import { createRoot } from 'solid-js';
import { insert, template, createComponent } from 'solid-js/web';
import { initialize, mswDecorator } from 'msw-storybook-addon';
import '../src/index.css';

export const decorators = [
  mswDecorator,
  (Story) =>
    createRoot(() => {
      const element = template('<div/>').cloneNode(true);
      insert(element, createComponent(Story, {}));
      return element;
    }),
];

export const parameters = {
  actions: {
    argTypesRegex: '^on[A-Z].*',
  },
  controls: {
    matchers: {
      color: /(background|color)$/i,
      date: /Date$/,
    },
  },
};
