// next-react-query/.storybook/preview.js
import '!style-loader!css-loader!postcss-loader!../src/styles/globals.css';
import { addDecorator } from '@storybook/react';
import { initialize, mswDecorator } from 'msw-storybook-addon';
import { RouterContext } from 'next/dist/shared/lib/router-context';

initialize();
addDecorator(mswDecorator);

export const parameters = {
  actions: { argTypesRegex: '^on[A-Z].*' },
  controls: {
    matchers: {
      color: /(background|color)$/i,
      date: /Date$/,
    },
  },
  nextRouter: {
    Provider: RouterContext.Provider,
  },
};

// solidjs-tailwind/.storybook/preview.js
import { createRoot } from 'solid-js';
import { insert, template, createComponent } from 'solid-js/web';
import { initialize, mswDecorator } from 'msw-storybook-addon';
import '../src/index.css';

export const decorators = [
  mswDecorator,
  (Story) =>
    createRoot(() => {
      const element = template('<div/>').cloneNode(true);
      insert(element, createComponent(Story, {}));
      return element;
    }),
];

export const parameters = {
  actions: {
    argTypesRegex: '^on[A-Z].*',
  },
  controls: {
    matchers: {
      color: /(background|color)$/i,
      date: /Date$/,
    },
  },
};
