// remix-gql-tailwind/app/components/Repositories/RepoAboutWidget/HomepageUrl.tsx
import { Link } from '@remix-run/react';
import { LinkIcon } from '@heroicons/react/outline';
import * as styles from './RepoAboutWidget.classNames';

interface HomepageUrlProps {
  homepageUrl?: string | null;
}

function HomepageUrl({ homepageUrl }: HomepageUrlProps) {
  if (!homepageUrl) {
    return null;
  }

  return (
    <div className={styles.linkContainer}>
      <LinkIcon className={styles.linkIcon} />
      <a href={homepageUrl} className={styles.link} target="_blank">
        {homepageUrl}
      </a>
    </div>
  );
}

export default HomepageUrl;

// qwik-graphql-tailwind/src/components/repo-about/homepage-url/index.tsx
import { component$ } from '@builder.io/qwik';
import { Link } from '@builder.io/qwik-city';
import { LinkIcon } from '~/components/icons';
import * as styles from '../repo-about.className';

interface HomepageUrlProps {
  homepageUrl?: string | null;
}

export const HomepageUrl = component$(({ homepageUrl }: HomepageUrlProps) => {
  if (!homepageUrl) {
    return null;
  }
  return (
    <div class={styles.linkContainer}>
      <LinkIcon className={styles.linkIcon} />
      <Link href={homepageUrl} class={styles.link} target="_blank">
        {homepageUrl}
      </Link>
    </div>
  );
});
