// solidstart-tanstackquery-tailwind-modules/src/components/RepoAbout/HomePageUrl.tsx
import { Show } from 'solid-js';
import { A } from 'solid-start';
import { LinkIcon } from '../Icons';
import styles from './RepoAbout.module.css';

interface HomepageUrlProps {
  homepageUrl: string;
}

export const HomepageUrl = (props: HomepageUrlProps) => {
  return (
    <Show when={props.homepageUrl}>
      <div class={styles.linkContainer}>
        <LinkIcon class={styles.linkIcon} />
        <A href={props.homepageUrl} class={styles.link} target="_blank">
          {props.homepageUrl}
        </A>
      </div>
    </Show>
  );
};

// qwik-graphql-tailwind/src/components/repo-about/homepage-url/index.tsx
import { component$ } from '@builder.io/qwik';
import { Link } from '@builder.io/qwik-city';
import { LinkIcon } from '~/components/icons';
import * as styles from '../repo-about.className';

interface HomepageUrlProps {
  homepageUrl?: string | null;
}

export const HomepageUrl = component$(({ homepageUrl }: HomepageUrlProps) => {
  if (!homepageUrl) {
    return null;
  }
  return (
    <div class={styles.linkContainer}>
      <LinkIcon className={styles.linkIcon} />
      <Link href={homepageUrl} class={styles.link} target="_blank">
        {homepageUrl}
      </Link>
    </div>
  );
});
