// solidstart-tanstackquery-tailwind-modules/src/components/FileExplorer/FileExplorer.tsx
import {
  createSignal,
  createEffect,
  For,
  Show,
  splitProps,
  Switch,
  Match,
} from 'solid-js';
import { DocumentIcon, FolderIcon } from '../Icons';
import styles from './FileExplorer.module.css';
import getRepoTree from '../../services/get-repo-tree';
import { parseQueryData } from './parseTree';
import { createQuery } from '@tanstack/solid-query';
import { TreeProps } from '~/types/repo-tree-type';

export type IProps = {
  branch: string;
  owner: string;
  name: string;
  path?: string;
};

const FileExplorerView = (props: IProps) => {
  const [local] = splitProps(props, ['path', 'name', 'owner', 'branch']);
  const [tree, setTree] = createSignal<TreeProps[]>([]);

  const basePath = () => `/${local.owner}/${local.name}`;

  const resTree = createQuery(
    () => [`${local.owner}_${local.name}_${local.branch}_${local.path || ''}`],
    () =>
      getRepoTree({
        owner: local.owner,
        name: local.name,
        expression: `${local.branch}:${local.path || ''}`,
      })
  );

  createEffect(() => {
    if (resTree.isSuccess && !resTree.isLoading && resTree.data.tree) {
      setTree(parseQueryData(resTree.data.tree));
    }
  });

  return (
    <Switch>
      <Match when={resTree.isLoading}>
        <div>Loading...</div>
      </Match>
      <Match when={resTree.isError}>
        <div>Error</div>
      </Match>
      <Match when={resTree.isSuccess && !resTree.isLoading}>
        <div class={styles.container}>
          <Show when={local.path && local.path !== ''}>
            <a
              href={`${basePath()}/tree/${local.branch}/${local.path}`}
              class={styles.cellBack}
              replace
            >
              <div class="text-blue-600">..</div>
            </a>
          </Show>
          <For each={tree()}>
            {(item) => (
              <div class={styles.cell}>
                <div class="flex items-center">
                  <div class="mr-2.5">
                    <Switch fallback={<DocumentIcon class={styles.iconFile} />}>
                      <Match when={item.type === 'tree'}>
                        <FolderIcon class={styles.iconDir} />
                      </Match>
                    </Switch>
                  </div>
                  <a
                    href={`${basePath()}/${item.type}/${local.branch}/${
                      item.path
                    }`}
                    data-testid={`file explorer list ${item.name}`}
                    class={styles.link}
                  >
                    {item.name}
                  </a>
                </div>
              </div>
            )}
          </For>
        </div>
      </Match>
    </Switch>
  );
};

export default FileExplorerView;

// qwik-graphql-tailwind/src/components/file-explorer/index.tsx
import { component$, useContext } from '@builder.io/qwik';
import { Link } from '@builder.io/qwik-city';
import { RepoContext } from '~/routes/[owner]/[name]/layout-named';
import { FolderIcon, DocumentIcon } from '~/components/icons';
import * as styles from './file-explorer.classNames';

export const FileExplorer = component$(() => {
  const store = useContext(RepoContext);

  const {
    branch,
    owner,
    name,
    path: repoPath,
    tree: { data },
  } = store;
  const basePath = `/${owner}/${name}`;
  const backLink = `${basePath}/tree/${branch}/${repoPath}`;

  return (
    <div className={styles.container}>
      {repoPath && (
        <a href={backLink}>
          <a className={styles.cellBack}>
            <div className="text-blue-600">..</div>
          </a>
        </a>
      )}
      {data?.tree?.map((item) => (
        <div key={item.path} className={styles.cell}>
          <div className="flex items-center">
            <div className="mr-2.5">
              {item.type === 'tree' ? (
                <FolderIcon className={styles.iconDir} />
              ) : (
                <DocumentIcon className={styles.iconFile} />
              )}
            </div>
            <Link href={`${basePath}/${item.type}/${branch}/${item.path}`}>
              <span className={styles.link}>{item.name}</span>
            </Link>
          </div>
        </div>
      ))}
    </div>
  );
});
