// remix-gql-tailwind/app/components/RepoHeader/RepoHeader.tsx
import RepoHeading from '../RepoHeading/RepoHeading';
import RepoActionButtons from '../RepoActionButtons/RepoActionButtons';
import TabNavigation from '../TabNavigation/TabNavigation';
import * as styles from './RepoHeader.classNames';
import { createTabList } from './tabList';
import { useRepo } from '../../context/RepoContext';

function RepoHeader() {
  const repo = useRepo();
  return (
    <div className={styles.wrapper}>
      <div className={styles.topRow}>
        <RepoHeading />
        <RepoActionButtons />
      </div>
      <div className={styles.bottomRow}>
        <TabNavigation
          tabs={createTabList({
            issueCount: repo.data?.openIssueCount,
            pullRequestCount: repo.data?.openPullRequestCount,
          })}
          basePath={`${repo.owner}/${repo.name}`}
          pathname={repo.pathname}
        />
      </div>
    </div>
  );
}

export default RepoHeader;

// solidstart-tanstackquery-tailwind-modules/src/components/RepoHeader/RepoHeader.tsx
import { useLocation, useParams } from '@solidjs/router';
import styles from './RepoHeader.module.css';
import { createTabList } from './tabList';
import { RepoHeading } from '../RepoHeading';
import { RepoActionButtons } from '../RepoActionButtons';
import { TabNavigation } from '../TabNavigation';
import { splitProps } from 'solid-js';
import { Info } from '~/types/repo-info-type';

function RepoHeader(props: Info) {
  const [local] = splitProps(props, [
    'openIssueCount',
    'openPullRequestCount',
    'forkCount',
    'isOrg',
    'stargazerCount',
    'watcherCount',
    'visibility',
  ]);
  const { pathname } = useLocation();
  const params = useParams();

  return (
    <div class={styles.wrapper}>
      <div class={styles.topRow}>
        <RepoHeading visibility={local.visibility} isOrg={local.isOrg} />
        <RepoActionButtons
          forkCount={local.forkCount}
          stargazerCount={local.stargazerCount}
          watcherCount={local.watcherCount}
        />
      </div>
      <div class={styles.bottomRow}>
        <TabNavigation
          tabs={createTabList({
            issueCount: local.openIssueCount,
            pullRequestCount: local.openPullRequestCount,
          })}
          basePath={`${params.owner}/${params.name}`}
          class="border-none"
          pathname={pathname}
        />
      </div>
    </div>
  );
}

export default RepoHeader;
