// next-react-query/src/components/RepoTabNavigation/tabList.tsx
import type { ComponentType } from 'react';
import { CodeIcon, InformationCircleIcon } from '@heroicons/react/outline';
import { PullRequestIcon } from '@components/Icons';

export interface TabItem {
  title: string;
  path?: string;
  Icon: ComponentType<{ className?: string }>;
}
export const tabList: TabItem[] = [
  {
    title: 'Code',
    path: '',
    Icon: CodeIcon,
  },
  {
    title: 'Issues',
    Icon: InformationCircleIcon,
  },
  {
    title: 'Pull Requests',
    Icon: PullRequestIcon,
  },
];

// solidstart-tanstackquery-tailwind-modules/src/components/RepoHeader/tabList.tsx
import { mergeProps } from 'solid-js';
import { PullRequestIcon, InformationCircleIcon, CodeIcon } from '../Icons';

type CreateTabListProps = {
  issueCount: number;
  pullRequestCount: number;
};

export function createTabList(props: CreateTabListProps) {
  const merged = mergeProps({ issuesCount: 0, pullRequestsCount: 0 }, props);

  return [
    {
      title: 'Code',
      path: '',
      Icon: CodeIcon,
    },
    {
      title: 'Issues',
      path: 'issues',
      Icon: InformationCircleIcon,
      // eslint-disable-next-line solid/reactivity
      count: merged.issueCount,
    },
    {
      title: 'Pull Requests',
      path: 'pulls',
      Icon: PullRequestIcon,
      // eslint-disable-next-line solid/reactivity
      count: merged.pullRequestCount,
    },
  ];
}
