// angular-ngrx-scss/src/app/home/profile/org-profile/org-info/org-info.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-org-info',
  templateUrl: './org-info.component.html',
  styleUrls: ['./org-info.component.scss'],
})
export class OrganizationInfoComponent {}

<div class="org-info-container">
  <a routerLink="/orgs/thisdot">
    <img
      [src]="'https://avatars.githubusercontent.com/u/22839396?v=4'"
      alt="organization logo"
    />
    <span class="title">This Dot</span>
  </a>
</div>

// svelte-kit-scss/src/lib/components/Profile/OrgInfo/OrgInfo.svelte
<div class="org-info-container col-span-12">
  <a href="/thisdot">
    <img
      src="https://avatars.githubusercontent.com/u/22839396?v=4"
      alt="thisdot logo"
    />
    <span class="title">This Dot</span>
  </a>
</div>

<style lang="scss">
  .org-info-container {
    a {
      display: flex;
      align-items: center;
      text-decoration: none;
      color: inherit;
      .title {
        font-weight: 700;
        font-size: 1.5rem;
        line-height: 2rem;
      }
      img {
        display: block;
        width: 32px;
        height: 32px;
        margin-right: 0.25rem;
        aspect-ratio: 1/1;
        border-radius: 0.25rem;
        box-sizing: content-box;
        background-color: white;
      }
    }
  }
</style>
