// cra-rxjs-styled-components/src/components/repo-filter/SearchInput.tsx
import { useRepoFilter } from '../../context/RepoFilterContext';
import { SearchTextInput } from './RepoFilter.styles';

export default function SearchInput() {
	const { search, setSearch } = useRepoFilter();

	const handleChange = (e: React.ChangeEvent<HTMLInputElement>) => {
		setSearch(e.target.value);
	};
	return (
		<SearchTextInput
			role="search"
			type="search"
			name="search"
			id="search"
			placeholder="Find a repository..."
			value={search}
			onInput={handleChange}
		/>
	);
}

// solidstart-tanstackquery-tailwind-modules/src/components/RepoFilter/SearchInput.tsx
import styles from './RepoFilter.module.css';
import { JSX } from 'solid-js';
import { search, setSearch } from './RepoFilter.store';

const SearchInput = () => {
  const handleChange: JSX.EventHandler<HTMLInputElement, InputEvent> = (
    e: InputEvent
  ) => {
    setSearch((e.target as HTMLInputElement).value);
  };

  return (
    <input
      data-testid="search-input"
      placeholder="find a repository.."
      role="search"
      type="search"
      value={search()}
      onInput={handleChange}
      class={styles.searchInput}
    />
  );
};

export default SearchInput;
