// nuxt-pinia-tailwind/pages/sign-in/index.vue
<template>
  <section class="h-screen w-full flex items-center justify-center bg-black">
    <form method="post" @submit="handleSignIn">
      <button
        type="submit"
        class="border-2 border-zinc-700 text-zinc-100 px-20 py-2 rounded-md hover:bg-zinc-100 hover:border-zinc-100 hover:text-zinc-900 transition-all"
      >
        Sign in with GitHub
      </button>
    </form>
  </section>
</template>

<script lang="ts">
import { useContext, defineComponent } from '@nuxtjs/composition-api'
import { SIGN_IN_URL } from '~/constants/url.constants'

export default defineComponent({
  name: 'SignIn',
  setup() {
    const {
      $config: { API_URL, BASE_URL },
    } = useContext()

    const handleSignIn = (event: Event): void => {
      event.preventDefault()
      window.location.href = SIGN_IN_URL(API_URL, BASE_URL)
    }

    return { handleSignIn }
  },
  head: {
    titleTemplate: '%s - Sign-in',
  },
  auth: false,
})
</script>

// qwik-graphql-tailwind/src/routes/auth/signin/index.tsx
import { component$ } from '@builder.io/qwik';
import type { DocumentHead } from '@builder.io/qwik-city';
import { SIGN_IN_URL } from '~/utils/constants';

export default component$(() => {
  return (
    <section className="flex h-screen w-full items-center justify-center bg-black">
      <button
        className="rounded-md border-2 border-zinc-700 px-20 py-2 text-zinc-100 transition-all hover:border-zinc-100 hover:bg-zinc-100 hover:text-zinc-900"
        onClick$={() => {
          window.location.href = SIGN_IN_URL;
        }}
      >
        Sign In with GitHub
      </button>
    </section>
  );
});

export const head: DocumentHead = {
  title: 'Authenticate with GitHub',
};
