// cra-rxjs-styled-components/src/components/user-profile/UserProfile.tsx
import {
	OfficeBuilding,
	LocationMarker,
} from '@styled-icons/heroicons-outline';
import { useUser } from '../../context/UserProvider';
import OrgList from './OrgList';
import { SocialIcons } from './SocialIcons';
import {
	Avatar,
	NameContainer,
	Name,
	Username,
	Bio,
	IconStyleWrapper,
	Fields,
	AnchorLink,
	TwitterIconStyles,
	LinkIconStyles,
} from './UserProfile.styles';

function UserProfileView() {
	const user = useUser();
	return (
		<div>
			<Avatar
				src={user?.avatar_url}
				alt="Avatar"
				width={260}
				height={260}
			></Avatar>
			<NameContainer>
				<Name>{user?.name}</Name>
				<Username>{user?.login}</Username>
			</NameContainer>
			<Bio>{user?.bio}</Bio>
			<IconStyleWrapper>
				{
					<SocialIcons
						followers={user?.followers}
						following={user?.following}
						starredRepos={user?.starredRepos}
					/>
				}
				<Fields>
					{user?.company && (
						<div>
							<OfficeBuilding />
							{user?.company}
						</div>
					)}
					{user?.location && (
						<div>
							<LocationMarker />
							{user?.location}
						</div>
					)}
					{user?.blog && (
						<div>
							<LinkIconStyles />
							<AnchorLink href={user?.blog} target="_blank" rel="noreferrer">
								{user?.blog}
							</AnchorLink>
						</div>
					)}
					{user?.twitter_username && (
						<div>
							<TwitterIconStyles />
							<AnchorLink
								href={`https:/twitter.com/${user?.twitter_username}`}
								target="_blank"
								rel="noreferrer"
							>
								@{user?.twitter_username}
							</AnchorLink>
						</div>
					)}
				</Fields>
			</IconStyleWrapper>
			{user?.organizations?.length && (
				<OrgList organizations={user?.organizations} />
			)}
		</div>
	);
}

export default UserProfileView;

// solidstart-tanstackquery-tailwind-modules/src/components/UserProfile/index.tsx
import {
  users,
  star,
  buildingOffice,
  mapPin,
  link,
} from 'solid-heroicons/outline';
import { Icon } from 'solid-heroicons';
import { TwitterIcon } from '../Icons';
import OrgList from './OrgList';
import styles from './UserProfile.module.css';
import { Show } from 'solid-js';

export interface UserProfileProps {
  avatarUrl: string;
  name: string;
  username: string;
  bio: string;
  followers: number;
  following: number;
  starredRepos: number;
  company: string;
  location: string;
  websiteUrl: string;
  twitterUsername: string;
  organizations: {
    nodes: {
      avatarUrl: string;
      name: string;
      login: string;
    }[];
  };
}

const UserProfile = (userProfileProps: UserProfileProps) => {
  return (
    <div>
      <img
        src={userProfileProps.avatarUrl}
        alt="Avatar"
        width={260}
        height={260}
        class={styles.avatar}
      />
      <h1 class="mt-2">
        <div class={styles.name}>{userProfileProps.name}</div>
        <div class={styles.username}>{userProfileProps.username}</div>
      </h1>
      <div class={styles.bio}>{userProfileProps.bio}</div>
      <div class={styles.socials}>
        <Icon path={users} class={styles.icon} />
        <span class="inline-block">
          <span class={styles.count}>{userProfileProps.followers}</span>{' '}
          followers
        </span>
        <span class="mx-1">·</span>
        <span class="inline-block">
          <span class={styles.count}>{userProfileProps.following}</span>{' '}
          following
        </span>
        <span class="mx-1">·</span>
        <Icon path={star} class={styles.icon} />
        <span class="inline-block">
          <span class={styles.count}>{userProfileProps.starredRepos}</span>{' '}
        </span>
      </div>
      <div class={styles.fields}>
        <Show when={userProfileProps.company}>
          <div>
            <Icon path={buildingOffice} class={styles.icon} />
            {userProfileProps.company}
          </div>
        </Show>
        <Show when={userProfileProps.location}>
          <div>
            <Icon path={mapPin} class={styles.icon} />
            {userProfileProps.location}
          </div>
        </Show>
        <Show when={userProfileProps.websiteUrl}>
          <div>
            <Icon path={link} class={styles.icon} />
            <a
              class={styles.link}
              href={userProfileProps.websiteUrl}
              target="_blank"
              rel="noreferrer"
            >
              {userProfileProps.websiteUrl}
            </a>
          </div>
        </Show>
        <Show when={userProfileProps.twitterUsername}>
          <div>
            <TwitterIcon class={styles.icon} />
            <a
              class={styles.link}
              href={`https:/twitter.com/${userProfileProps.twitterUsername}`}
              target="_blank"
              rel="noreferrer"
            >
              @{userProfileProps.twitterUsername}
            </a>
          </div>
        </Show>
      </div>
      <Show when={userProfileProps.organizations.nodes.length > 0}>
        <OrgList organizations={userProfileProps.organizations.nodes} />
      </Show>
    </div>
  );
};

export default UserProfile;
