// solidjs-tailwind/src/components/RepoActionButtons/CountButtonGroup.jsx
import { children } from "solid-js";
import styles from './RepoActionButtons.module.css';

const formatCountString = (props) => {
  const count = () => props || 0;
  let countText = `${count()}`;
  if (count() && count() > 1000) {
    let digits = countText.split('');
    digits.splice(digits.length - 3, 3);
    countText = `${digits.join('')}k`;
  }
  return countText;
};

function CountButtonGroup(props) {
  const count = () => props.count || 0;
  let countText = formatCountString(count());
  const c = children(() => props.children);
  let buttonText = c().toString()
    .replace('[object Object],', '')
    .toLowerCase();
  return (
    <span class={styles.btnGroup}>
      <button type="button" class={styles.btnMain}>
        {props.children}
      </button>
      <button
        data-testid={`repo ${buttonText} count`}
        type="button"
        class={styles.btnSide}
      >
        {countText}
      </button>
    </span>
  );
}

export default CountButtonGroup;

// remix-gql-tailwind/app/components/RepoActionButtons/CountButtonGroup.tsx
import type { ReactNode } from "react";
import * as styles from "./RepoActionButtons.classNames";

interface CountButtonGroupProps {
  children: ReactNode;
  count?: number;
}

const formatCountString = (count: number) => {
  let countText = `${count}`;
  if (count && count > 1000) {
    let digits = countText.split("");
    digits.splice(digits.length - 3, 3);
    countText = `${digits.join("")}k`;
  }
  return countText;
};

function CountButtonGroup({ children, count = 0 }: CountButtonGroupProps) {
  let countText = formatCountString(count);
  return (
    <span className={styles.btnGroup}>
      <button type="button" className={styles.btnMain}>
        {children}
      </button>
      <button type="button" className={styles.btnSide}>
        {countText}
      </button>
    </span>
  );
}

export default CountButtonGroup;
