// solidjs-tailwind/src/components/RepoFilter/FilterText.jsx
import { Show, splitProps } from 'solid-js';
import { CloseIcon } from '../Icons';
import { defaultFilterType, defaultLanguage } from './data';
import { filterType, language, search, sortBy } from './RepoFilter.store';
import styles from './RepoFilter.module.css';

const modifyFilterTypeText = (filterText = 'test') => {
  if (filterText.endsWith('s')) {
    if (filterText.match(new RegExp('forks', 'i'))) {
      filterText = filterText.replace('s', 'ed');
    } else {
      filterText = filterText.replace('s', '');
    }
  }
  return filterText;
};

const FilterText = (props) => {
  const [local] = splitProps(props, [
    'filteredRepoCount',
    'setFilterType',
    'setLanguage',
  ]);

  const clearFilters = () => {
    local.setFilterType(defaultFilterType);
    local.setLanguage(defaultLanguage);
  };

  return (
    <div class={styles.filterTextContainer}>
      <div class="flex-grow">
        <small class={styles.filterText}>
          <strong>{local.filteredRepoCount}</strong>
          results for
          <Show when={filterType() && filterType() !== defaultFilterType}>
            <strong>{modifyFilterTypeText(filterType())}</strong>
          </Show>{' '}
          repositories
          <Show when={search()}>
            <span>
              matching <strong> {search()} </strong>
            </span>
          </Show>
          <Show when={language() && language() !== defaultLanguage}>
            <span>
              written in
              <strong> {language()} </strong>
            </span>
          </Show>
          <span>
            sorted by
            <strong>{' ' + sortBy()}</strong>
          </span>
        </small>
      </div>
      <div onClick={() => clearFilters()}>
        <a class={styles.clearFilter}>
          <span class={styles.closeIconSpan}>
            <CloseIcon />
          </span>
          Clear filter
        </a>
      </div>
    </div>
  );
};

export default FilterText;

// cra-rxjs-styled-components/src/components/repo-filter/FilterText.tsx
import { useRepoFilter } from '../../context/RepoFilterContext';
import { defaultFilterType, defaultLanguage } from './data';
import { CloseIcon } from '../icons';
import {
	ClearButtonContainer,
	ClearButtonText,
	FilterTextContainer,
	FilterTextSmall,
} from './RepoFilter.styles';

const modifyFilterTypeText = (filterText = 'test') => {
	if (filterText.endsWith('s')) {
		if (filterText.match(new RegExp('forks', 'i'))) {
			filterText = filterText.replace('s', 'ed');
		} else {
			filterText = filterText.replace('s', '');
		}
	}
	return filterText;
};

type FilterTextProps = {
	filteredRepoCount?: number;
};

const FilterText = (props: FilterTextProps) => {
	const { filteredRepoCount } = props;
	const { filterType, search, language, sortBy, resetFilter } = useRepoFilter();

	return (
		<FilterTextContainer>
			<div className="flex-grow">
				<FilterTextSmall>
					<strong>{filteredRepoCount}</strong>
					results for
					{filterType && filterType !== defaultFilterType && (
						<strong>{modifyFilterTypeText(filterType)}</strong>
					)}{' '}
					repositories
					{search && (
						<span>
							matching <strong> {search} </strong>
						</span>
					)}
					{language && language !== defaultLanguage && (
						<span>
							written in
							<strong> {language} </strong>
						</span>
					)}
					<span>
						sorted by
						<strong>{' ' + sortBy}</strong>
					</span>
				</FilterTextSmall>
			</div>
			<ClearButtonContainer onClick={resetFilter}>
				<ClearButtonText>
					<CloseIcon />
				</ClearButtonText>
				Clear filter
			</ClearButtonContainer>
		</FilterTextContainer>
	);
};

export default FilterText;
