// remix/app/components/IssueFilters/Pagination.tsx
import type { IssueFilterAPI } from './useIssueFilters';
import type { PageInfo } from './types';
import { ChevronRightIcon, ChevronLeftIcon } from '@heroicons/react/outline';
import * as styles from './Pagination.classNames';

interface PaginationProps {
  pageInfo?: PageInfo;
  changePage: IssueFilterAPI['changePage'];
}

function Pagination({ pageInfo, changePage }: PaginationProps) {
  const nextPage = () => {
    changePage({ after: pageInfo?.endCursor });
  };

  const previousPage = () => {
    changePage({ before: pageInfo?.startCursor });
  };

  return (
    <div className={styles.container}>
      <span className={styles.group}>
        <button
          type="button"
          disabled={!pageInfo?.hasPreviousPage || !pageInfo.startCursor}
          onClick={previousPage}
          className={styles.button}
        >
          <ChevronLeftIcon className="w-4 h-4 inline mr-1.5" />
          Previous
        </button>
        <button
          type="button"
          onClick={nextPage}
          disabled={!pageInfo?.hasNextPage || !pageInfo.endCursor}
          className={styles.button}
        >
          Next
          <ChevronRightIcon className="w-4 h-4 inline ml-1.5" />
        </button>
      </span>
    </div>
  );
}

export default Pagination;

// angular-apollo-tailwind/src/app/components/pagination/pagination.component.ts
import { Component, EventEmitter, Input, Output } from '@angular/core';
import { PageInfo, PaginationEvent } from '../../gql';

@Component({
  selector: 'app-pagination',
  templateUrl: './pagination.component.html',
  styleUrls: ['./pagination.component.css'],
})
export class PaginationComponent {
  @Input() pageInfo: PageInfo | null = null;

  @Output() changePage: EventEmitter<PaginationEvent> = new EventEmitter();

  handlePreviousPageClick() {
    this.changePage.emit({
      before: this.pageInfo?.startCursor,
    });
  }

  handleNextPageClick() {
    this.changePage.emit({
      after: this.pageInfo?.endCursor,
    });
  }
}

<div class="paginator-container">
  <span class="group">
    <button
      type="button"
      [disabled]="!pageInfo?.hasPreviousPage"
      (click)="handlePreviousPageClick()"
      class="button"
    >
      <!-- <hero-icon
        name="chevron-left"
        type="outline"
        class="w-4 h-4 inline mr-1.5"
        aria-hidden="true"
      ></hero-icon> -->
      Previous
    </button>
    <button
      type="button right"
      [disabled]="!pageInfo?.hasNextPage"
      (click)="handleNextPageClick()"
      class="button"
    >
      Next
      <!-- <hero-icon
        name="chevron-right"
        type="outline"
        class="w-4 h-4 inline ml-1.5"
        aria-hidden="true"
      ></hero-icon> -->
    </button>
  </span>
</div>
