// next-react-query/src/context/RepoContext.tsx
import type { ReactNode } from 'react';
import { createContext, useContext } from 'react';

export interface RepoContext {
  name: string;
  owner: string;
  branch: string;
  path: string;
  isRepoLoading?: boolean;
  data?: {
    isPrivate: boolean;
    stargazerCount: number;
    forkCount: number;
    watcherCount: number;
    description?: string | null;
  };
}

interface RepoProviderProps {
  children: ReactNode;
  value: RepoContext;
}

export const RepoContext = createContext<RepoContext | undefined>(undefined);

export function RepoProvider({ children, value }: RepoProviderProps) {
  return (
    <RepoContext.Provider
      value={{
        isRepoLoading: false,
        ...value,
      }}
    >
      {children}
    </RepoContext.Provider>
  );
}

export function useRepo() {
  const context = useContext(RepoContext);
  if (context === undefined) {
    throw new Error('useRepo must be used within a RepoPage');
  }
  return context;
}

// solidjs-tailwind/src/contexts/RepoContext.jsx
import { createSignal, createEffect,  createContext, useContext } from "solid-js";

const RepoContext = createContext();

export function RepoProvider(props) {
  const [readme, setReadme] = createSignal({error: undefined,  text: undefined, isLoading: false});

  createEffect(() => {
    setReadme(props.readme)
  });

  const repo = [
    readme
  ]

  return (
    <RepoContext.Provider value={repo}>
      {props.children}
    </RepoContext.Provider>
  );
}

export function useRepo() {
  return useContext(RepoContext);
}
