// angular-apollo-tailwind/src/app/file-viewer/repo-read-me/repo-read-me.component.ts
import {
  ChangeDetectionStrategy,
  Component,
  Input,
  OnInit,
} from '@angular/core';
import { map, Observable } from 'rxjs';
import { RepoReadMeGQL } from 'src/app/gql';

@Component({
  selector: 'app-repo-read-me',
  templateUrl: './repo-read-me.component.html',
  styleUrls: ['./repo-read-me.component.css'],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class RepoReadMeComponent implements OnInit {
  @Input() owner = '';
  @Input() name = '';
  @Input() fileName = '';
  @Input() path = '';

  readme$!: Observable<{ text?: string | null }>;

  constructor(private repoReadMeGQL: RepoReadMeGQL) {}

  ngOnInit(): void {
    this.readme$ = this.repoReadMeGQL
      .watch({
        owner: this.owner,
        name: this.name,
        expression: this.buildPathExpression(),
      })
      .valueChanges.pipe(
        map((res) => {
          const readMeNode = res?.data?.repository?.readme;
          const text =
            readMeNode?.__typename === 'Blob' ? readMeNode.text : null;

          return {
            text,
          };
        }),
      );
  }

  private buildPathExpression(): string {
    const path = this.path ? `${this.path}/${this.fileName}` : this.fileName;
    return `HEAD:${path}`;
  }
}

<div *ngIf="readme$ | async as readme">
  <ng-container *ngIf="readme.text as text; else empty">
    <div class="read-me-container" data-testid="readme">
      <header class="header">
        <span class="tocIconContainer">
          <svg
            xmlns="http://www.w3.org/2000/svg"
            viewBox="0 0 16 16"
            width="16"
            height="16"
            class="tocIcon"
            fill="currentColor"
          >
            <path
              fillRule="evenodd"
              d="M2 4a1 1 0 100-2 1 1 0 000 2zm3.75-1.5a.75.75 0 000 1.5h8.5a.75.75 0 000-1.5h-8.5zm0 5a.75.75 0 000 1.5h8.5a.75.75 0 000-1.5h-8.5zm0 5a.75.75 0 000 1.5h8.5a.75.75 0 000-1.5h-8.5zM3 8a1 1 0 11-2 0 1 1 0 012 0zm-1 6a1 1 0 100-2 1 1 0 000 2z"
            ></path>
          </svg>
        </span>
        <span class="filename">README.md</span>
      </header>
      <article
        class="prose py-6 px-10 max-w-none prose-headings:font-medium prose-p:my-3 prose-p:leading-6 prose-headings:border-b prose-headings:my-1 prose-headings:pb-2 prose-h1:my-4 prose-h2:my-4 prose-h3:border-none prose-h4:border-none prose-h5:border-none prose-img:inline prose-img:m-0 prose-a:text-blue-600 prose-a:no-underline prose-a:font-normal hover:prose-a:underline prose-li:my-0.5 prose-pre:bg-gray-100 prose-code:text-gray-800 text-gray-800"
      >
        <app-read-me [text]="text"></app-read-me>
      </article>
    </div>
  </ng-container>

  <ng-template #empty>
    <div class="emptyContainer">
      <div class="emptyText">
        Help people interested in this repository understand your project by
        adding a README.
      </div>
      <button class="addReadmeBtn">Add a README</button>
    </div>
  </ng-template>
</div>

// qwik-graphql-tailwind/src/components/repo-read-me/index.tsx
import { component$, useContext } from '@builder.io/qwik';
import { useLocation } from '@builder.io/qwik-city';
import { Markdown } from '~/integrations/react/read-md';
import { RepoContext } from '~/routes/[owner]/[name]/layout-named';

import * as styles from './repo-read-me.className';
import { TOCIcon } from '../icons';
import { Empty } from './empty';

export const RepoReadMe = component$(() => {
  const store = useContext(RepoContext);
  const { pathname } = useLocation();

  if (store.readme.text) {
    return (
      <div className={styles.container} data-testid="readme">
        <header className={styles.header}>
          <span className={styles.tocIconContainer}>
            <TOCIcon className={styles.tocIcon} />
          </span>
          <span className={styles.filename}>README.md</span>
        </header>
        <article className="prose py-6 px-10 max-w-none prose-headings:font-medium prose-p:my-3 prose-p:leading-6 prose-headings:border-b prose-headings:my-1 prose-headings:pb-2 prose-h1:my-4 prose-h2:my-4 prose-h3:border-none prose-h4:border-none prose-h5:border-none prose-img:inline prose-img:m-0 prose-a:text-blue-600 prose-a:no-underline prose-a:font-normal hover:prose-a:underline prose-li:my-0.5 prose-pre:bg-gray-100  prose-code:text-gray-800 text-gray-800 prose-code:px-1 prose-code:py-0.5 prose-code:rounded-md prose-code:bg-gray-100">
          <Markdown data={store.readme.text} />
        </article>
      </div>
    );
  }

  if (!pathname.includes('tree')) {
    return <Empty />;
  }

  return null;
});
