// angular-ngrx-scss/src/app/shared/components/pagination/pagination.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-pagination',
  templateUrl: './pagination.component.html',
  styleUrls: ['./pagination.component.scss'],
})
export class PaginationComponent {}

<div class="paginator-container">
  <span class="group">
    <button
      type="button"
      class="button"
      [disabled]="!canPrev"
      (click)="prevPage()"
    >
      Previous
    </button>
    <button
      type="button"
      class="button"
      [disabled]="!canNext"
      (click)="nextPage()"
    >
      Next
    </button>
  </span>
</div>

// cra-rxjs-styled-components/src/components/pagination/Pagination.tsx
import { PaginationContainer } from './Pagination.styles';

export default function Pagination() {
  return (
    <PaginationContainer>
      <div className="group">
        <button className="button" disabled>
          Previous
        </button>
        <button className="button">Next</button>
      </div>
    </PaginationContainer>
  );
}
