// solidjs-tailwind/src/components/UserDropdown/UserDropdown.jsx
import { NavLink } from '@solidjs/router';
import { createSignal } from 'solid-js';
import { ChevronDownIcon } from '@heroicons/react/solid';
import { clickOutside } from '../../utils/onclick-outside';
import * as styles from './user-dropdown.classNames';

const UserDropdown = (props) => {
  const [expanded, setExpanded] = createSignal(false);

  const signOut = () => {
    // TODO: sign out
  };

  return (
    <div use:clickOutside={() => setExpanded(false)}>
      <div class={styles.dropdown}>
        <button
          role="button"
          class={styles.dropdownBtn}
          onClick={() => setExpanded(!expanded())}
        >
          <div class={styles.avatarContainer}>
            {props.image && (
              <img
                src={props.image}
                alt="Profile Photo"
                width={32}
                height={32}
              />
            )}
          </div>
          <div class="w-4 ml-1">
            <ChevronDownIcon />
          </div>
        </button>
        <nav
          class={
            expanded() ? styles.dropdownMenuBase : styles.dropdownMenuHidden
          }
        >
          <ul class="py-1">
            {props.username && (
              <li data-menu-item>
                <NavLink
                  href={`/${props.username}`}
                  class={styles.menuBtn}
                >
                  Profile
                </NavLink>
              </li>
            )}
            <li data-menu-item>
              <button class={styles.menuBtn}>Sign Out</button>
            </li>
          </ul>
        </nav>
      </div>
    </div>
  );
};

export default UserDropdown;

// qwik-graphql-tailwind/src/components/user-dropdown/userDropdown.tsx
import { $, component$, useStore } from '@builder.io/qwik';
import { Link } from '@builder.io/qwik-city';
import { ChevronDownIcon } from '../icons';
import * as styles from './userDropdown.classNames';

export interface UserDropdownProps {
  image?: string | null;
  username?: string;
}

export const UserDropdown = component$(({ image, username }: UserDropdownProps) => {
  const store = useStore({
    expanded: false,
  });

  const toggle$ = $(() => {
    store.expanded = !store.expanded;
  });

  return (
    <div>
      <div className={styles.dropdown}>
        <button role="button" className={styles.dropdownBtn} onClick$={toggle$}>
          <div className={styles.avatarContainer}>
            {image && <img src={image} alt="Profile Photo" width={32} height={32} />}
          </div>
          <div class="w-4 ml-1">
            <ChevronDownIcon />
          </div>
        </button>
        <nav className={store.expanded ? styles.dropdownMenuBase : styles.dropdownMenuHidden}>
          <ul className="py-1">
            {username && (
              <li>
                <Link href={`/${username}`} className={styles.menuBtn}>
                  Profile
                </Link>
              </li>
            )}
            <li>
              <button className={styles.menuBtn}>Sign Out</button>
            </li>
          </ul>
        </nav>
      </div>
      {store.expanded ? <div className={styles.overlay} onClick$={toggle$}></div> : null}
    </div>
  );
});
