// solidstart-tanstackquery-tailwind-modules/src/components/UserDropdown/UserDropdown.tsx
import { A } from '@solidjs/router';
import { createSignal, Show } from 'solid-js';
import { ChevronDownIcon } from '../Icons';
import { clickOutside } from '../../utils/onclickOutside';
import styles from './UserDropdown.module.css';

interface IProps {
  image: string;
  username: string;
}

const UserDropdown = (props: IProps) => {
  const [expanded, setExpanded] = createSignal(false);

  const _clickOutside = clickOutside;

  return (
    // @ts-ignore
    <div use:_clickOutside={() => setExpanded(false)}>
      <div class={styles.dropdown}>
        <button
          role="button"
          class={styles.dropdownBtn}
          onClick={() => setExpanded(!expanded())}
        >
          <div class={styles.avatarContainer}>
            <Show when={props.image}>
              <img
                src={props.image}
                alt="Profile Photo"
                width={32}
                height={32}
              />
            </Show>
          </div>
          <ChevronDownIcon class="-mr-1 ml-2 h-3 w-3" aria-hidden="true" />
        </button>
        <nav
          class={
            expanded() ? styles.dropdownMenuBase : styles.dropdownMenuHidden
          }
        >
          <ul class="py-1">
            <Show when={props.username}>
              <li data-menu-item>
                <A
                  href={`/${props.username}`}
                  class={styles.menuBtn}
                  onClick={() => setExpanded(false)}
                >
                  Profile
                </A>
              </li>
            </Show>
            <li data-menu-item>
              <button class={styles.menuBtn}>Sign Out</button>
            </li>
          </ul>
        </nav>
      </div>
    </div>
  );
};

export default UserDropdown;

// qwik-graphql-tailwind/src/components/user-dropdown/userDropdown.tsx
import { $, component$, useStore } from '@builder.io/qwik';
import { Link } from '@builder.io/qwik-city';
import { ChevronDownIcon } from '../icons';
import * as styles from './userDropdown.classNames';

export interface UserDropdownProps {
  image?: string | null;
  username?: string;
}

export const UserDropdown = component$(({ image, username }: UserDropdownProps) => {
  const store = useStore({
    expanded: false,
  });

  const toggle$ = $(() => {
    store.expanded = !store.expanded;
  });

  return (
    <div>
      <div className={styles.dropdown}>
        <button role="button" className={styles.dropdownBtn} onClick$={toggle$}>
          <div className={styles.avatarContainer}>
            {image && <img src={image} alt="Profile Photo" width={32} height={32} />}
          </div>
          <div class="w-4 ml-1">
            <ChevronDownIcon />
          </div>
        </button>
        <nav className={store.expanded ? styles.dropdownMenuBase : styles.dropdownMenuHidden}>
          <ul className="py-1">
            {username && (
              <li>
                <Link href={`/${username}`} className={styles.menuBtn}>
                  Profile
                </Link>
              </li>
            )}
            <li>
              <button className={styles.menuBtn}>Sign Out</button>
            </li>
          </ul>
        </nav>
      </div>
      {store.expanded ? <div className={styles.overlay} onClick$={toggle$}></div> : null}
    </div>
  );
});
