// qwik-graphql-tailwind/src/components/filter-dropdown/filter-dropdown.tsx
import { $, component$, useSignal, useStore } from '@builder.io/qwik';
import { CheckIcon, ChevronDownIcon, XmarkIcon } from '../icons';
import * as styles from './filter-dropdown.classNames';
import cn from 'classnames';

interface Option {
  label: string;
  value: number | string | null;
}

interface FilterDropdownProps {
  name: string;
  description?: string;
  current: number | string | null;
  items: Option[];
  onChange: (value: any) => void;
  buttonClassName?: string;
}

export const FilterDropdown = component$(
  ({ name, description, current, items, buttonClassName }: FilterDropdownProps) => {
    const elementRef = useSignal<HTMLElement | undefined>(undefined);

    const store = useStore({
      expanded: false,
    });

    const toggle$ = $(() => {
      store.expanded = !store.expanded;
    });

    const close$ = $(() => {
      store.expanded = false;
    });

    return (
      <div
        document:onClick$={(event) => {
          if (!isParentWithinScope(event.target as HTMLElement, elementRef.value)) {
            close$();
          }
        }}
      >
        <div className={styles.container} ref={elementRef}>
          <div>
            <button type="button" className={buttonClassName || styles.menuButton} onClick$={toggle$}>
              {name}
              <ChevronDownIcon className={styles.menuButtonIcon} aria-hidden="true" />
            </button>
          </div>

          <nav
            className={cn(styles.dropdownMenuBase, !store.expanded ? styles.dropdownMenuHidden : '')}
            data-testid="filterDropdown"
          >
            <div>
              {description && (
                <div className={styles.menuHeader}>
                  <div className={styles.description}>{description}</div>
                  <button type="button">
                    <XmarkIcon className={styles.closeButtonIcon} aria-hidden="true" />
                  </button>
                </div>
              )}
              {items.map(({ label, value }) => (
                <div>
                  <button type="button" name={name} className={styles.itemButton}>
                    {value === current && <CheckIcon className={styles.itemActiveIcon} />} {label}
                  </button>
                </div>
              ))}
            </div>
          </nav>
        </div>
      </div>
    );
  }
);

export function isParentWithinScope(target: HTMLElement, element: HTMLElement | undefined): boolean {
  if (target === element) {
    return true;
  }
  if (target.parentElement) {
    return isParentWithinScope(target.parentElement, element);
  }
  return false;
}

// remix-gql-tailwind/app/components/RepoFilters/FilterDropdown.tsx
import { Fragment } from "react";
import { Menu, Transition } from "@headlessui/react";
import { ChevronDownIcon, XIcon, CheckIcon } from "@heroicons/react/solid";
import * as styles from "./FilterDropdown.classNames";

interface Option {
  label: string;
  value: number | string;
}

interface DropdownProps {
  name: string;
  description?: string;
  current: number | string;
  items: Option[];
  onChange: (value: any) => void;
}

function Dropdown({
  name,
  description,
  current,
  items,
  onChange,
}: DropdownProps) {
  return (
    <Menu as="div" className={styles.container}>
      <div>
        <Menu.Button className={styles.menuButton}>
          {name}
          <ChevronDownIcon
            className={styles.menuButtonIcon}
            aria-hidden="true"
          />
        </Menu.Button>
      </div>
      <Transition
        as={Fragment}
        enter="transition ease-out duration-100"
        enterFrom="transform opacity-0 scale-95"
        enterTo="transform opacity-100 scale-100"
        leave="transition ease-in duration-75"
        leaveFrom="transform opacity-100 scale-100"
        leaveTo="transform opacity-0 scale-95"
      >
        <Menu.Items className={styles.menu}>
          <div>
            {description && (
              <div className={styles.menuHeader}>
                <div className={styles.description}>{description}</div>
                <Menu.Button>
                  <XIcon
                    className={styles.closeButtonIcon}
                    aria-hidden="true"
                  />
                </Menu.Button>
              </div>
            )}
            {items.map(({ label, value }) => (
              <Menu.Item key={value}>
                <button
                  type="button"
                  className={styles.itemButton}
                  onClick={() => {
                    onChange(value);
                  }}
                >
                  {value === current && (
                    <CheckIcon className={styles.itemActiveIcon} />
                  )}{" "}
                  {label}
                </button>
              </Menu.Item>
            ))}
          </div>
        </Menu.Items>
      </Transition>
    </Menu>
  );
}

export default Dropdown;
