// next-react-query-tailwind/src/components/FileExplorerNav/FileExplorerNav.tsx
import { GitBranchIcon } from '@components/Icons';
import Link from 'next/link';
import { useRepo } from '@context/RepoContext';
import styles from './FileExplorerNav.module.css';

function RepoNavigation() {
  const { name, owner, path, branch } = useRepo();
  const crumbs = path.split('/').filter(Boolean);
  return (
    <nav className={styles.container}>
      <button className={styles.btn}>
        <GitBranchIcon className={styles.btnIcon} /> {branch}{' '}
        <span className={styles.btnCaret}>{'\u25BC'}</span>
      </button>
      {crumbs.length > 0 && (
        <div className={styles.crumbs}>
          <Link href={`/${owner}/${name}`}>
            <a className={styles.rootLink}>{name}</a>
          </Link>
          <span className={styles.separator}>/</span>
          {crumbs.map((crumb, i) => {
            const isLast = i === crumbs.length - 1;
            const crumbPath = crumbs.slice(0, i + 1).join('/');
            const href = `/${owner}/${name}/tree/${branch}/${crumbPath}`;
            return (
              <>
                {isLast ? (
                  <span className={styles.crumbEnd}>{crumb}</span>
                ) : (
                  <>
                    <Link href={`/${href}`}>
                      <a className={styles.crumbLink}>{crumb}</a>
                    </Link>
                    <span className={styles.separator}>/</span>
                  </>
                )}
              </>
            );
          })}
        </div>
      )}
    </nav>
  );
}

export default RepoNavigation;

// angular-apollo-tailwind/src/app/file-viewer/file-explorer-nav/file-explorer-nav.component.ts
import { ChangeDetectionStrategy, Component, Input } from '@angular/core';

@Component({
  selector: 'app-file-explorer-nav',
  templateUrl: './file-explorer-nav.component.html',
  styleUrls: ['./file-explorer-nav.component.css'],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class FileExplorerNavComponent {
  @Input() basePath = '';
  @Input() name = '';
  @Input() branch = 'master';
  @Input() set path(val: string | undefined) {
    this.crumbs = val?.split('/').filter(Boolean) as string[];
  }

  crumbs: string[] = [];

  getHerf(i: number): string {
    const crumbPath = this.crumbs.slice(0, i + 1).join('/');
    return `/${this.basePath}/tree/${this.branch}/${crumbPath}`;
  }
}

<nav class="container">
  <button class="btn">
    <app-git-branch-icon class="btnIcon"></app-git-branch-icon>
    {{ branch }}
    <span class="btnCaret">&#9660;</span>
  </button>
  <div *ngIf="crumbs.length" class="crumbs">
    <a [routerLink]="basePath" class="rootLink">{{ name }}</a>
    <span class="separator">/</span>
    <div *ngFor="let crumb of crumbs; let i = index">
      <ng-container *ngIf="i === crumbs.length - 1; else hasCrumb">
        <span class="crumbEnd">{{ crumb }}</span>
      </ng-container>

      <ng-template #hasCrumb>
        <a [routerLink]="getHerf(i)" class="crumbLink">{{ crumb }}</a>
        <span class="separator">/</span>
      </ng-template>
    </div>
  </div>
</nav>
