// svelte-kit-scss/src/lib/components/RepoControls/RepoControls.svelte
<script lang="ts">
  import FilterDropdown from '$lib/components/FilterDropdown/FilterDropdown.svelte';
  import { writable } from 'svelte/store';
  import { OrderField, TypeFilter } from '../../constants/filters';

  const repoControlsInit = {
    searchInput: '',
    typeFilter: TypeFilter.All,
    languageFilter: TypeFilter.All,
    sortFilter: OrderField.UpdatedAt,
  };
  let hasActiveSortAndFilters;
  const repoControls = writable(repoControlsInit);

  function handleTypeClick(event: CustomEvent<TypeFilter>) {
    repoControls.update((prevValue) => ({ ...prevValue, typeFilter: event.detail }));
  }

  function handleLanguageClick(event: CustomEvent<TypeFilter>) {
    repoControls.update((prevValue) => ({ ...prevValue, languageFilter: event.detail }));
  }

  function handleSortClick(event: CustomEvent<OrderField>) {
    repoControls.update((prevValue) => ({ ...prevValue, sortFilter: event.detail }));
  }

  function handleClearClick(): void {
    repoControls.set(repoControlsInit);
  }
</script>

<section>
  <div class="controls">
    <input
      id="searchInput"
      aria-label="Search repository"
      type="search"
      placeholder="Find a repository..."
      bind:value={$repoControls.searchInput}
    />

    <!--      TODO: fix the "current" input for this and the rest in this file-->
    <FilterDropdown
      name="Type"
      description="Select type"
      items={$repoControls.typeFilters}
      current="selectFilterByType$ | async"
      on:setFilter={repoControlsInit}
    />
    <FilterDropdown
      name="Language"
      description="Select Language"
      [current]="selectFilterByLanguage$ | async"
      items={$repoControls.languageFilter}
      on:setFilter={handleLanguageClick}
    />
    <FilterDropdown
      name="Sort"
      description="Select sort"
      [items]="sortItems"
      [current]="selectSortFilter$ | async"
      items={$repoControls.sortItems}
      on:setFilter={handleSortClick}
    />
  </div>
</section>

<style lang="scss">
  @use 'src/lib/styles/variables';

  section {
    margin: 1.3em 0 0 2.5em;
  }

  .controls {
    display: flex;
    justify-content: flex-end;
    align-items: center;
    gap: 0.6em;
    margin-bottom: 1.2em;

    input {
      flex-grow: 1;
      margin-right: 0.6em;
      padding: 0.4rem;
      border-radius: 0.4rem;
      border: 1px solid variables.$gray200;
      line-height: 1.5rem;
    }

    .control-dropdown {
      display: inline-flex;
      align-items: center;
      border-radius: 0.375rem;
      border: 1px solid variables.$gray300;
      background-color: variables.$gray100;
      padding: 0.375rem 1rem;
      line-height: 1.25rem;
      color: variables.$gray900;

      &__name {
        font-weight: 600;
      }

      &__caret {
        margin-left: 0.25em;
      }
    }
  }

  .divider {
    width: 100%;
    height: 2px;
    background: variables.$gray100;
  }

  .results {
    display: flex;
    margin-bottom: 0.25rem;
    justify-content: flex-end;
    align-items: center;
    gap: 0.4rem;

    &__text {
      flex-grow: 1;
    }

    &__clear {
      background: none;
      border: none;
      padding: 0;
      font: inherit;
      cursor: pointer;
      display: flex;
      align-items: center;
      gap: 0.5rem;
      color: variables.$gray500;
      &:hover {
        color: variables.$blue600;
      }
      &__icon {
        background: variables.$gray500;
        border-radius: 0.3rem;
        width: 1.4rem;
        height: 1.4rem;
        display: grid;
        place-items: center;
      }
      &:hover &__icon {
        background: variables.$blue600;
      }
    }
  }
</style>

// angular-ngrx-scss/src/app/shared/components/repo-controls/repo-controls.component.ts
import { Component, OnDestroy, OnInit } from '@angular/core';
import { FormControl } from '@angular/forms';
import { Store } from '@ngrx/store';
import {
  debounceTime,
  distinctUntilChanged,
  combineLatest,
  Subject,
} from 'rxjs';
import { startWith, takeUntil } from 'rxjs/operators';
import { setSortAndFilterProperties } from 'src/app/state/profile/profile.actions';
import {
  filteredLanguages,
  hasActiveSortAndFilters,
  isActiveFilterByLanguage,
  isActiveFilterByType,
  selectFilterByLanguage,
  selectFilterBySearch,
  selectFilterByType,
  selectReposCount,
  selectSortFilter,
} from 'src/app/state/profile/profile.selectors';
import {
  OrderField,
  SortAndFilterState,
  TypeFilter,
} from 'src/app/state/profile/profile.state';

const TYPE_FILTERS = [
  {
    label: 'All',
    value: TypeFilter.All,
  },
  {
    label: 'Forks',
    value: TypeFilter.Forked,
  },
  {
    label: 'Archived',
    value: TypeFilter.Archived,
  },
];

const SORT_ITEMS = [
  {
    label: 'Last updated',
    value: OrderField.UpdatedAt,
  },
  { value: OrderField.Name, label: 'Name' },
  { value: OrderField.Stargazers, label: 'Stars' },
];

@Component({
  selector: 'app-repo-controls',
  templateUrl: './repo-controls.component.html',
  styleUrls: ['./repo-controls.component.scss'],
})
export class RepoControlsComponent implements OnInit, OnDestroy {
  private readonly destroy$ = new Subject<boolean>();

  searchInput = new FormControl('');
  typeFilter = new FormControl(TypeFilter.All);
  languageFilter = new FormControl(TypeFilter.All);
  sortFilter = new FormControl(OrderField.UpdatedAt);
  hasActiveSortAndFilters$ = this.store.select(hasActiveSortAndFilters);

  selectReposCount$ = this.store.select(selectReposCount);

  isActiveFilterByType$ = this.store.select(isActiveFilterByType);
  isActiveFilterByLanguage$ = this.store.select(isActiveFilterByLanguage);

  selectFilterBySearch$ = this.store.select(selectFilterBySearch);
  selectFilterByType$ = this.store.select(selectFilterByType);
  selectFilterByLanguage$ = this.store.select(selectFilterByLanguage);
  filteredLanguages$ = this.store
    .select(filteredLanguages)
    .pipe((languages) => languages ?? []);
  selectSortFilter$ = this.store.select(selectSortFilter);

  readonly typeFilters = TYPE_FILTERS;
  readonly sortItems = SORT_ITEMS;

  constructor(private store: Store) {}

  ngOnInit(): void {
    const searchInput$ = this.searchInput.valueChanges.pipe(
      debounceTime(200),
      distinctUntilChanged(),
      startWith(''),
    );

    const typeFilter$ = this.typeFilter.valueChanges.pipe(
      distinctUntilChanged(),
      startWith(TypeFilter.All),
    );

    const languageFilter$ = this.languageFilter.valueChanges.pipe(
      distinctUntilChanged(),
      startWith(TypeFilter.All),
    );

    const sortFilter$ = this.sortFilter.valueChanges.pipe(
      distinctUntilChanged(),
      startWith(null),
    );

    combineLatest(
      [searchInput$, typeFilter$, languageFilter$, sortFilter$],
      (search: string, type: string, language: string, sort: string) => ({
        search,
        type,
        language,
        sort,
      }),
    )
      .pipe(takeUntil(this.destroy$))
      .subscribe((filters: SortAndFilterState) => {
        this.store.dispatch(setSortAndFilterProperties({ filters }));
      });
  }

  ngOnDestroy(): void {
    this.destroy$.next(true);
    this.destroy$.complete();
  }

  handleTypeClick(type: string) {
    this.typeFilter.setValue(type);
  }

  handleLanguageClick(language: string) {
    this.languageFilter.setValue(language);
  }

  handleSortClick(sort: string) {
    this.sortFilter.setValue(sort);
  }

  handleClearClick(): void {
    this.searchInput.reset();
    this.typeFilter.setValue(TypeFilter.All);
    this.languageFilter.setValue(TypeFilter.All);
    this.sortFilter.setValue(OrderField.UpdatedAt);
  }
}

<section>
  <div class="controls">
    <input
      id="searchInput"
      aria-label="Search repository"
      type="search"
      placeholder="Find a repository..."
      [formControl]="searchInput"
    />
    <app-filter-dropdown
      name="Type"
      description="Select type"
      [items]="typeFilters"
      [current]="selectFilterByType$ | async"
      (setFilter)="handleTypeClick($event)"
    ></app-filter-dropdown>
    <app-filter-dropdown
      name="Language"
      description="Select Language"
      [items]="(filteredLanguages$ | async) || []"
      (setFilter)="handleTypeClick($event)"
    ></app-filter-dropdown>
    <app-filter-dropdown
      name="Sort"
      description="Select type"
      [items]="typeFilters"
      (setFilter)="handleTypeClick($event)"
    ></app-filter-dropdown>
  </div>
  <ng-container *ngIf="hasActiveSortAndFilters$ | async">
    <div class="divider"></div>
    <div class="results">
      <p class="results__text">
        <span class="bold">{{ selectReposCount$ | async }}</span>
        results
        <ng-container *ngIf="isActiveFilterByType$ | async">
          for <span class="bold">{{ selectFilterByType$ | async }}</span>
        </ng-container>
        <ng-container *ngIf="selectFilterBySearch$ | async as search">
          matching <span class="bold">{{ search }}</span>
        </ng-container>
        <ng-container *ngIf="isActiveFilterByLanguage$ | async as language">
          written in
          <span class="bold">
            {{ selectFilterByLanguage$ | async | titlecase }}
          </span>
        </ng-container>
        sorted by updated at
      </p>
      <span
        class="results__clear-container"
        (click)="handleClearFiltersClick()"
      >
        <div class="close-background">
          <span appOcticon="x" color="white" size="13"></span>
        </div>
        <p class="results__clear">Clear filter</p>
      </span>
    </div>
    <div class="divider"></div>
  </ng-container>
</section>
