// solidjs-tailwind/src/components/AuthGuard/AuthGuard.jsx
import ROUTES from '../../routes';
import { useAuth } from '../../auth';
import { useNavigate, useLocation } from '@solidjs/router';
import { Show, children } from 'solid-js';

const AuthGuard = (props) => {
  const navigate = useNavigate();
  const location = useLocation();
  const { authStore } = useAuth();
  const c = children(() => props.children);

  if (!authStore.isAuthenticated) {
    sessionStorage.setItem('auth_return_path', location.pathname);
    navigate(ROUTES.SIGNIN, { replace: true });
  }

  return <Show when={authStore.isAuthenticated}>{c()}</Show>;
};

export default AuthGuard;

// cra-rxjs-styled-components/src/components/AuthGuard.tsx
import { Navigate, useLocation } from 'react-router-dom';
import { AUTH_TOKEN } from '../constants/auth.constants';

export default function AuthGuard({ children }: { children: JSX.Element }) {
	const location = useLocation();

	const isAuthenticated = sessionStorage.getItem(AUTH_TOKEN);
	if (!isAuthenticated) {
		return <Navigate to="/signin" state={{ from: location }} />;
	}
	return children;
}
