// solidjs-tailwind/src/components/Header/Header.jsx
import { NavLink } from '@solidjs/router';
import { splitProps } from 'solid-js';
import { UserDropdown } from '../UserDropdown';

import { GithubLogo } from './GithubLogo';
import * as styles from './Header.classNames';

const Header = (props) => {
  const [local] = splitProps(props, ['user'])
    return (
        <header class={styles.header}>
          <NavLink href="/">
            <GithubLogo />
          </NavLink>
          <div>
            {local.user ? (
              <UserDropdown
                image={local.user.avatarUrl}
                username={local.user.login}
              />
            ) : (
              <NavLink href="/api/auth/signin">
                <span class={styles.navLink}>Sign In</span>
              </NavLink>
            )}
          </div>
        </header>
    );
};

export default Header;

// qwik-graphql-tailwind/src/components/header/header.tsx
import { component$ } from '@builder.io/qwik';
import { Link } from '@builder.io/qwik-city';
import { UserDropdown } from '../user-dropdown/userDropdown';
import { GitHubLogo } from './github-logo';

import * as styles from './header.classNames';

type HeaderProps = {
  user: {
    avatarUrl: string;
    login: string;
  } | null;
};

export default component$(({ user }: HeaderProps) => {
  return (
    <header className={styles.header}>
      <Link href="/">
        <GitHubLogo />
      </Link>
      <div>
        {user ? (
          <UserDropdown image={user.avatarUrl} username={user.login} />
        ) : (
          <Link href="/api/auth/signin">
            <span className={styles.navLink}>Sign In</span>
          </Link>
        )}
      </div>
    </header>
  );
});
