// qwik-graphql-tailwind/src/components/repo-heading/index.tsx
import { component$ } from '@builder.io/qwik';
import { RepoIcon } from '../icons/repo.icon';

interface RepoHeadingProps {
  name: string;
  owner: string;
}

export const RepoHeading = component$(({ name, owner }: RepoHeadingProps) => {
  const profile_url = `/${owner}`;
  const repo_url = `/${owner}/${name}`;
  return (
    <h1 className="flex items-center text-xl leading-7">
      <RepoIcon className="w-6 h-6 text-gray-600" />
      <span className="text-[#2563EB] inline-block ml-2.5 mb-0.5">
        <a>{owner}</a>
        <a href={profile_url} className="hover:underline">
          {owner}
        </a>
        <span className="text-black ml-1.5">/</span>
        <a className="font-semibold ml-1.5">{name}</a>
        <a href={repo_url} className="font-semibold ml-1.5 hover:underline">
          {name}
        </a>
      </span>
    </h1>
  );
});

// angular-apollo-tailwind/src/app/repo/repo-heading/repo-heading.component.ts
import { Component, OnInit } from '@angular/core';
// import { useRepo } from '@context/RepoContext';

@Component({
  selector: 'app-repo-heading',
  templateUrl: './repo-heading.component.html',
})
export class RepoHeadingComponent implements OnInit {
  constructor() {}
  // const { owner, name, data } = useRepo();
  ngOnInit(): void {}
}

<!-- TODO: useRepo in component.ts -->
<h1 class="space-x-2.5 flex items-center text-xl">
  <app-privacy-icon [isPrivate]={{data?.isPrivate}}></app-privacy-icon>
  <span class="space-x-1.5 mb-0.5">
    <a class="text-blue-600 hover:underline">{{owner}}</a>
    <span class="text-gray-600">/</span>
    <a [routerLink]="[owner, name]">
      <a class="text-blue-600 font-semibold hover:underline">{{name}}</a>
    </a>
  </span>
  <app-privacy-badge [isPrivate]={{data?.isPrivate}}></app-privacy-badge>
</h1>
