// angular-apollo-tailwind/src/app/file-viewer/file-explorer/file-explorer.component.ts
import { ChangeDetectionStrategy, Component, Input } from '@angular/core';

const removeLastPathPart = (path: string) => {
  const pathParts = path.split('/');
  return pathParts.slice(0, pathParts.length - 1).join('/');
};

@Component({
  selector: 'app-file-explorer',
  templateUrl: './file-explorer.component.html',
  styleUrls: ['./file-explorer.component.css'],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class FileExplorerComponent {
  @Input() items: any[] = [];
  @Input() branch: string = '';
  @Input() basePath: string = '';
  @Input() repoPath: string = '';
  @Input() isLoaded: boolean = false;

  getBackLink(repoPath: string) {
    const backPath = removeLastPathPart(repoPath);
    return `${this.basePath}/tree/${this.branch}/${backPath}`;
  }

  getPathHref(item: any): string {
    return `${this.basePath}/${item.type}/${this.branch}/${item.path}`;
  }
}

<div class="container">
  <a *ngIf="repoPath" [routerLink]="getBackLink(repoPath)" class="cellBack">
    <span class="text-blue-600">..</span>
  </a>
  <div *ngFor="let item of items" class="cell">
    <div class="flex items-center">
      <div class="mr-2.5">
        <ng-container *ngIf="item.type === 'tree'; else file">
          <app-folder-icon class="iconDir"></app-folder-icon>
        </ng-container>
        <ng-template #file>
          <app-document-icon class="iconFile"></app-document-icon>
        </ng-template>
      </div>
      <a [routerLink]="getPathHref(item)" class="link">{{ item.name }}</a>
    </div>
  </div>
</div>

<!-- TODO: fix loading indicator -->
<!-- <ng-template #loading>
  <div class="container py-2">
    <app-loading-bullet-list></app-loading-bullet-list>
  </div>
</ng-template> -->

// solidjs-tailwind/src/components/FileExplorer/FileExplorer.jsx
import { For } from 'solid-js';
import { Link } from '@solidjs/router';
import { removeLastPathPart } from '../../utils/removeLastPathPart';
import { document } from 'solid-heroicons/outline';
import { folder } from 'solid-heroicons/solid';
import { Icon } from 'solid-heroicons';
import styles from './FileExplorer.module.css';

const FileExplorerView = (props) => {
  return (
    <div class={styles.container}>
      {props.repoPath && (
        <Link
          href={`${props.basePath}/tree/${props.branch}/${removeLastPathPart(
            props.repoPath
          )}`}
        >
          <a class={styles.cellBack}>
            <div class="text-blue-600">..</div>
          </a>
        </Link>
      )}
      <For each={props.items}>
        {(item) => (
          <div class={styles.cell}>
            <div class="flex items-center">
              <div class="mr-2.5">
                {item.type === 'tree' ? (
                  <Icon path={folder} class={styles.iconDir} />
                ) : (
                  <Icon path={document} class={styles.iconFile} />
                )}
              </div>
              <Link
                href={`${props.basePath}/${item.type}/${props.branch}/${item.path}`}
              >
                <a
                  data-testid={`file explorer list ${item.name}`}
                  class={styles.link}
                >
                  {item.name}
                </a>
              </Link>
            </div>
          </div>
        )}
      </For>
    </div>
  );
};

export default FileExplorerView;
