// angular-apollo-tailwind/src/app/components/loading/loading-pulse-dots/loading-pulse-dots.component.ts
import { Component } from '@angular/core';

@Component({
	selector: 'app-loading-pulse-dots',
	template: `<div class="flex space-x-1">
		<div class="bg-gray-600 w-2 h-2 rounded-full animate-bounce delay-10"></div>
		<div class="bg-gray-600 w-2 h-2 rounded-full animate-bounce delay-20"></div>
		<div class="bg-gray-600 w-2 h-2 rounded-full animate-bounce delay-30"></div>
	</div>`,
})
export class LoadingPulseDotsComponent {}

// next-react-query-tailwind/src/components/Loading/LoadingPulseDots.tsx
function LoadingPulseDots() {
  return (
    <div className="flex space-x-1">
      <div
        style={{ animationDelay: '0.1s' }}
        className="bg-gray-600 w-2 h-2 rounded-full animate-bounce"
      ></div>
      <div
        style={{ animationDelay: '0.2s' }}
        className="bg-gray-600 w-2 h-2 rounded-full animate-bounce"
      ></div>
      <div
        style={{ animationDelay: '0.3s' }}
        className="bg-gray-600 w-2 h-2 rounded-full animate-bounce"
      ></div>
    </div>
  );
}

export default LoadingPulseDots;
