// qwik-graphql-tailwind/src/components/repo-heading/index.tsx
import { component$, useContext } from '@builder.io/qwik';
import { RepoContext } from '~/routes/[owner]/[name]/layout-named';
import { RepoIcon } from '../icons/repo.icon';

export const RepoHeading = component$(() => {
  const store = useContext(RepoContext);

  const profile_url = `/${store.owner}`;
  const repo_url = `/${store.owner}/${store.name}`;
  return (
    <h1 class="flex items-center text-xl leading-7">
      <RepoIcon className="w-6 h-6 text-gray-600" />
      <span class="text-[#2563EB] inline-block ml-2.5 mb-0.5">
        <a href={profile_url} class="hover:underline">
          {store.owner}
        </a>
        <span class="text-black ml-1.5">/</span>
        <a href={repo_url} class="font-semibold ml-1.5 hover:underline">
          {store.name}
        </a>
      </span>
    </h1>
  );
});

// angular-apollo-tailwind/src/app/repo-heading/repo-heading.component.ts
import { Component, OnInit } from '@angular/core';
// import { useRepo } from '@context/RepoContext';

@Component({
  selector: 'app-repo-header',
  templateUrl: './repo-header.component.html',
  styleUrls: ['./repo-header.component.css'],
})
export class RepoHeadingComponent implements OnInit {
  constructor() {}
  // const { owner, name, data } = useRepo();
  ngOnInit(): void {}
}

<!-- TODO: Privacy Icon -->
<h1 class="space-x-2.5 flex items-center text-xl">
  <PrivacyIcon isPrivate={{data?.isPrivate}} />
  <span class="space-x-1.5 mb-0.5">
    <a class="text-blue-600 hover:underline">{{owner}}</a>
    <span class="text-gray-600">/</span>
    <a [routerLink]="[owner, name]">
      <a class="text-blue-600 font-semibold hover:underline">{{name}}</a>
    </a>
  </span>
  <app-privacy-badge isPrivate={{data?.isPrivate}} />
</h1>
