// expo-zustand-styled-components/src/screens/Repository/Pull-Requests/Pull-Requests.tsx
import React, { useEffect } from 'react';
import { Wrapper } from './Pull-Requests.style';
import {
  usePRAndIssueHeaderStore,
  usePullRequestsStore,
  useRepoInfoStore,
} from '../../../hooks/stores';
import { DEFAULT_PAGE_SIZE, SORT_OPTIONS } from '../../../utils/constants';
import { parseSortParams } from '../../../utils/parseSortParams';
import getRepoPullRequests from '../../../services/get-repo-pull-requests';
import PRAndIssueLoaderSkeleton from '../../../components/PRAndIssueLoaderSkeleton';
import PullRequestsTabView from '../../../components/PullRequestsTabView';

const PullRequest = () => {
  const { after, before, isLoading, pullRequests } = usePullRequestsStore();
  const { sortBy, label, setLabels } = usePRAndIssueHeaderStore();
  const { name, owner } = useRepoInfoStore();

  const fetchParameters = () => ({
    owner,
    name,
    orderBy: parseSortParams(SORT_OPTIONS, sortBy, 0),
    direction: parseSortParams(SORT_OPTIONS, sortBy, 1),
    labels: label ? [label] : undefined,
    before: typeof before === 'string' ? before : undefined,
    after: typeof after === 'string' ? after : undefined,
    first: after || !before ? DEFAULT_PAGE_SIZE : undefined,
    last: before ? DEFAULT_PAGE_SIZE : undefined,
  });

  useEffect(() => {
    if (!isLoading) {
      setLabels(pullRequests.labels);
    }
  }, [isLoading]);

  useEffect(() => {
    getRepoPullRequests(fetchParameters());
  }, [before, sortBy, label, after]);
  return (
    <Wrapper>
      {isLoading ? <PRAndIssueLoaderSkeleton cardType="pr" /> : <PullRequestsTabView />}
    </Wrapper>
  );
};

export default PullRequests;

// vue3-apollo-quasar/src/views/Repository/PullRequests/PullRequests.vue
<template>
  <pull-request-wrapper :pullRequestsData="pullRequestsData" />
</template>

<script lang="ts">
import { usePullRequest } from '@/composables';
import { computed, defineComponent, defineProps, ref, watch } from 'vue';

export default defineComponent({
  name: 'PullRequests',
});
</script>

<script lang="ts" setup>
import { DEFAULT_PAGE_SIZE, parseSortParams, SORT_OPTIONS } from '@/helpers';
import { useRepoStore } from '@/store/respoStore';
import { PullRequestResp } from '@/composables/github/types';
import { useRoute } from 'vue-router';
import PullRequestWrapper from './PullRequestWrapper.vue';

const props = defineProps({
  owner: {
    type: String,
    default: '',
  },
  repo: {
    type: String,
    default: '',
  },
});
const repoStore = useRepoStore();

const {
  query,
}: {
  query: {
    before?: string;
    after?: string;
  };
} = useRoute();
const pullRequestsData = ref<{ value: PullRequestResp }>();
const isLoading = ref<boolean>(true);
const { getPullRequests, getPullRequestsRestAPI } = usePullRequest();

watch(
  [
    () => repoStore.selectedLabel,
    () => repoStore.selectedMilestone,
    () => repoStore.sortBy,
    () => props.owner,
    () => props.repo,
    () => query.before,
    () => query.after,
  ],
  async () => {
    isLoading.value = true;
    repoStore.setLoading(isLoading);
    if (repoStore.selectedMilestone) {
      const data = await getPullRequestsRestAPI({
        owner: props.owner,
        name: props.repo,
        orderBy: parseSortParams(SORT_OPTIONS, repoStore.sortBy, 0),
        direction: parseSortParams(SORT_OPTIONS, repoStore.sortBy, 1),
        labels: repoStore.selectedLabel ? [repoStore.selectedLabel] : undefined,
        milestone: repoStore.selectedMilestone,
        before: query.before,
        after: query.after,
        first: query.after || !query.before ? DEFAULT_PAGE_SIZE : undefined,
        last: query.before ? DEFAULT_PAGE_SIZE : undefined,
      });
      isLoading.value = false;
      repoStore.setLoading(isLoading);
      const resp = computed(() => data);
      pullRequestsData.value = resp;
    } else {
      const { data: respData, loading } = getPullRequests({
        owner: props.owner,
        name: props.repo,
        orderBy: parseSortParams(SORT_OPTIONS, repoStore.sortBy, 0),
        direction: parseSortParams(SORT_OPTIONS, repoStore.sortBy, 1),
        labels: repoStore.selectedLabel ? [repoStore.selectedLabel] : undefined,
        milestone: repoStore.selectedMilestone,
        before: query.before,
        after: query.after,
        first: query.after || !query.before ? DEFAULT_PAGE_SIZE : undefined,
        last: query.before ? DEFAULT_PAGE_SIZE : undefined,
      });

      isLoading.value = false;
      repoStore.setLoading(loading);
      pullRequestsData.value = respData;
    }
  },
  {
    immediate: true,
  },
);
</script>

<style lang="scss" scoped>
.pullrequest-section {
  max-width: 70rem;
}
</style>
