// angular-ngrx-scss/src/app/auth/auth.component.ts
import { Component } from '@angular/core';
import { FormControl, FormGroup } from '@angular/forms';
import { AuthService } from './services/auth.service';

@Component({
  selector: 'app-auth',
  templateUrl: './auth.component.html',
  styleUrls: ['./auth.component.scss'],
})
export class AuthComponent {
  signInGroup = new FormGroup({
    csrfToken: new FormControl(''),
    callbackUrl: new FormControl(''),
  });

  constructor(private authService: AuthService) {}

  onSubmit() {
    this.authService.signIn().subscribe(({ redirectUrl }) => {
      window.location.href = redirectUrl;
    });
  }
}

<div class="page">
  <div class="sign-in">
    <div class="provider">
      <form class="form" [formGroup]="signInGroup" (ngSubmit)="onSubmit()">
        <input type="hidden" class="input" formControlName="csrfToken" />
        <input type="hidden" class="input" formControlName="callbackUrl" />
        <button type="submit" class="button">Sign in with GitHub</button>
      </form>
    </div>
  </div>
</div>

// svelte-kit-scss/src/lib/components/auth/Auth.svelte
<script lang="ts">
  import { AuthService } from "$lib/services";
  import { getContext } from "svelte";
  const authService = getContext<AuthService>(AuthService);
  const onSubmit = () => {
    authService.signIn();
  }
</script>

<form on:submit|preventDefault={onSubmit}>
  <input type="hidden" class="input" name="csrfToken" />
  <input type="hidden" class="input" name="callbackUrl" />
  <button type="submit" class="button">Sign in with GitHub</button>
</form>

<style lang="scss">
</style>
