// angular-ngrx-scss/src/app/home/user-gists/user-gists.component.ts
import { Component } from '@angular/core';
import { Store } from '@ngrx/store';

import { selectGists } from 'src/app/state/profile/profile.selectors';

@Component({
  selector: 'app-user-gists',
  templateUrl: './user-gists.component.html',
  styleUrls: ['./user-gists.component.scss'],
})
export class UserGistsComponent {
  userGists$ = this.store.select(selectGists);

  constructor(private store: Store) {}
}

<div class="container">
  <h3>Gists</h3>
  <ng-container *ngIf="userGists$ | async as gists">
    <ng-container *ngIf="gists.length > 0; else noGists">
      <ul>
        <ng-container *ngFor="let gist of gists">
          <li>
            <a class="link" [href]="gist.url" target="_blank">{{
              gist.fileName
            }}</a>
          </li>
        </ng-container>
      </ul>
    </ng-container>
  </ng-container>
</div>

<ng-template #noGists>
  <p>User does not have any gists</p>
</ng-template>

// solidjs-tailwind/src/components/UserGists/UserGists.jsx
import { Link } from '@solidjs/router';
import { For } from 'solid-js';
import Container from './Container';
import styles from './UserGists.module.css';

const UserGists = (props) => {
  return (
    <Container>
      <div class="mt-3">
        {props.gists.length > 0 ? (
          <For each={props.gists}>
            {(gist) => (
              <div class="my-1">
                <Link href={gist.url} class={styles.link} target="_blank">
                  {gist.name}
                </Link>
              </div>
            )}
          </For>
        ) : (
          <p class={styles.error}>User does not have any gists</p>
        )}
      </div>
    </Container>
  );
};

export default UserGists;
