// angular-apollo-tailwind/src/app/file-viewer/file-viewer/file-viewer.component.ts
import { Component, Input } from '@angular/core';
import { ActivatedRoute, ParamMap } from '@angular/router';
import { map, Observable, switchMap } from 'rxjs';
import { FileDetails, RepoFileGQL } from 'src/app/gql';
import { mapLanguageExt } from '../utils/map-language-ext';

@Component({
  selector: 'app-file-viewer',
  templateUrl: './file-viewer.component.html',
  styleUrls: ['./file-viewer.component.css'],
})
export class FileViewerComponent {
  @Input() owner = '';
  @Input() name = '';
  @Input() branch = '';

  file$: Observable<FileDetails> = this.route.paramMap.pipe(
    map((params: ParamMap) => params.get('path') as string),
    switchMap((path: string) =>
      this.repoFileGQL
        .watch({
          owner: this.owner,
          name: this.name,
          expression: `${this.branch}:${path ?? ''}`,
        })
        .valueChanges.pipe(
          map((res) => {
            const file = res?.data?.repository?.blob;
            const extension = path?.split('.').pop() as string;
            const language = mapLanguageExt(extension);
            const text = file?.__typename === 'Blob' ? file.text : '';
            const byteSize = file?.__typename === 'Blob' ? file.byteSize : '';
            const lines = text ? text.split('\n').length : 0;

            return {
              path,
              byteSize,
              extension,
              language,
              text,
              lines,
            };
          }),
        ),
    ),
  );

  constructor(
    private route: ActivatedRoute,
    private repoFileGQL: RepoFileGQL,
  ) {}
}

<ng-container *ngIf="!errorLoadFile; else errorLoadFileTmpl">
  <div
    content
    *ngIf="file$ | async as file; else loading"
    class="file-viewer-container"
  >
    <div class="fileHeader">
      <span data-testid="file viewer line count" class="fileHeaderLines"
        >{{ file.lines }} lines</span
      >
      <span data-testid="file viewer byte size" class="fileHeaderBytes"
        >{{ file.byteSize }} Bytes</span
      >
    </div>
    <ng-container *ngIf="file.language; else unknownLanguage">
      <app-file-code
        [text]="file.text!"
        [language]="file.language"
      ></app-file-code>
    </ng-container>
    <ng-template #unknownLanguage>
      <app-file-text [text]="file.text!"></app-file-text>
    </ng-template>
  </div>

  <ng-template #loading>
    <div class="file-viewer-container py-2">
      <sd-code-icon
        type="outline"
        [width]="400"
        [height]="100"
        viewBox="-20 0 400 80"
      ></sd-code-icon>
    </div>
  </ng-template>
</ng-container>

<ng-template #errorLoadFileTmpl>
  <sd-error-block>An error occurred while loading file.</sd-error-block>
</ng-template>

// solidjs-tailwind/src/components/FileViewer/FileViewer.jsx
import { createResource } from 'solid-js';
import { useParams } from '@solidjs/router';
import styles from './FileViewer.module.css';
import { useRepo } from '../../contexts/RepoContext';
import getRepoFile from '../../services/get-repo-file';
import FileCode from './FileCode';
import FileText from './FileText';
import { mapExtensionToLanguage } from './mapExtensionToLanguage';

const FileViewer = () => {
  const { info } = useRepo();
  const params = useParams();

  const branch = params.branch || info().branch;
  const path = params.path;

  const [resBlob] = createResource(`${branch}_${params.path}`, () =>
    getRepoFile({
      owner: params.owner,
      name: params.name,
      expression: `${branch}:${params.path || ''}`,
    })
  );

  const extension = path.split('.').pop();
  const language = mapExtensionToLanguage(extension);

  return (
    <>
      {resBlob.loading ? (
        <div>Loading...</div>
      ) : (
        <div class={styles.container}>
          <div class={styles.fileHeader}>
            <span
              data-testid="file viewer line count"
              class={styles.fileHeaderLines}
            >
              {resBlob().text?.split('\n').length} lines
            </span>
            <span
              data-testid="file viewer byte size"
              class={styles.fileHeaderBytes}
            >
              {resBlob().byteSize} Bytes
            </span>
          </div>
          {language ? (
            <FileCode text={resBlob().text} language={language} />
          ) : (
            <FileText text={resBlob().text} />
          )}
        </div>
      )}
    </>
  );
};

export default FileViewer;
