// angular-ngrx-scss/src/app/file-viewer/file-viewer/file-viewer.component.ts
import {
  ChangeDetectionStrategy,
  Component,
  Input,
  OnInit,
} from '@angular/core';
import { FileContents } from '../../state/repository';
import { mapLanguageExt } from '../utils/map-lanuage-ext';
import { Language } from '@prism';

@Component({
  selector: 'app-file-viewer',
  templateUrl: './file-viewer.component.html',
  styleUrls: ['./file-viewer.component.scss'],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class FileViewerComponent implements OnInit {
  @Input() fileContent!: FileContents;
  extension!: string;
  language!: Language;
  lines!: number;

  ngOnInit(): void {
    this.extension = this.fileContent.name.split('.').pop() as string;
    this.language = mapLanguageExt(this.extension);
    this.lines = this.fileContent.content
      ? this.fileContent.content.split('\n').length
      : 0;
  }
}

<div
  content
  *ngIf="fileContent"
  class="file-viewer-container"
>
  <div class="fileHeader">
      <span data-testid="file viewer line count" class="fileHeaderLines"
      >{{ lines }} lines</span
      >
    <span data-testid="file viewer byte size" class="fileHeaderBytes"
    >{{ fileContent.size }} Bytes</span
    >
  </div>
  <ng-container *ngIf="language; else unknownLanguage">
    <app-file-code
      [text]="fileContent.content"
      [language]="language"
    ></app-file-code>
  </ng-container>
  <ng-template #unknownLanguage>
    <app-file-text [text]="fileContent.content"></app-file-text>
  </ng-template>
</div>

// solidjs-tailwind/src/components/FileViewer/FileViewer.jsx
import { createResource } from 'solid-js';
import { useParams } from '@solidjs/router';
import styles from './FileViewer.module.css';
import { useRepo } from '../../contexts/RepoContext';
import getRepoFile from '../../services/get-repo-file';
import FileCode from './FileCode';
import FileText from './FileText';
import { mapExtensionToLanguage } from './mapExtensionToLanguage';

const FileViewer = () => {
  const { info } = useRepo();
  const params = useParams();

  const branch = params.branch || info().branch;
  const path = params.path;

  const [resBlob] = createResource(`${branch}_${params.path}`, () =>
    getRepoFile({
      owner: params.owner,
      name: params.name,
      expression: `${branch}:${params.path || ''}`,
    })
  );

  const extension = path.split('.').pop();
  const language = mapExtensionToLanguage(extension);

  return (
    <>
      {resBlob.loading ? (
        <div>Loading...</div>
      ) : (
        <div class={styles.container}>
          <div class={styles.fileHeader}>
            <span
              data-testid="file viewer line count"
              class={styles.fileHeaderLines}
            >
              {resBlob().text?.split('\n').length} lines
            </span>
            <span
              data-testid="file viewer byte size"
              class={styles.fileHeaderBytes}
            >
              {resBlob().byteSize} Bytes
            </span>
          </div>
          {language ? (
            <FileCode text={resBlob().text} language={language} />
          ) : (
            <FileText text={resBlob().text} />
          )}
        </div>
      )}
    </>
  );
};

export default FileViewer;
