// angular-ngrx-scss/src/app/file-viewer/file-explorer-nav/file-explorer-nav.component.ts
import {
  ChangeDetectionStrategy,
  Component,
  Input,
  OnInit,
} from '@angular/core';

@Component({
  selector: 'app-file-explorer-nav',
  templateUrl: './file-explorer-nav.component.html',
  styleUrls: ['./file-explorer-nav.component.scss'],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class FileExplorerNavComponent implements OnInit {
  @Input() owner = '';
  @Input() name = '';
  @Input() branch = 'master';

  @Input() set path(val: string | undefined) {
    this.crumbs = val?.split('/').filter(Boolean) as string[];
  }

  basePath = '';
  crumbs: string[] = [];

  ngOnInit(): void {
    this.basePath = `/${this.owner}/${this.name}`;
  }

  getHref(i: number): string {
    const crumbPath = this.crumbs.slice(0, i + 1).join('/');
    return `${this.basePath}/tree/${this.branch}/${crumbPath}`;
  }
}

<nav class="file-explorer-container">
  <button class="btn">
    <span class="icon" appOcticon="git-branch"></span>
    {{ branch }}
    <span class="btnCaret">&#9660;</span>
  </button>
  <div *ngIf="crumbs.length" class="crumbs">
    <a
      [attr.data-testid]="'file explorer nav root ' + name"
      [routerLink]="[basePath]"
      class="rootLink"
    >{{ name }}</a
    >
    <span class="separator">/</span>
    <div *ngFor="let crumb of crumbs; let i = index">
      <ng-container *ngIf="i === crumbs.length - 1; else hasCrumb">
        <span
          [attr.data-testid]="'file explorer nav end ' + crumb"
          class="crumbEnd"
        >{{ crumb }}</span
        >
      </ng-container>

      <ng-template #hasCrumb>
        <a
          [attr.data-testid]="'file explorer nav crumb ' + crumb"
          [routerLink]="getHref(i)"
          class="crumbLink"
        >{{ crumb }}</a
        >
        <span class="separator">/</span>
      </ng-template>
    </div>
  </div>
</nav>

// next-react-query-tailwind/src/components/FileExplorerNav/FileExplorerNav.tsx
import { GitBranchIcon } from '@components/Icons';
import Link from 'next/link';
import { useRepo } from '@context/RepoContext';
import styles from './FileExplorerNav.module.css';

function RepoNavigation() {
  const { name, owner, path, branch } = useRepo();
  const crumbs = path.split('/').filter(Boolean);
  return (
    <nav className={styles.container}>
      <button className={styles.btn}>
        <GitBranchIcon className={styles.btnIcon} /> {branch}{' '}
        <span className={styles.btnCaret}>{'\u25BC'}</span>
      </button>
      {crumbs.length > 0 && (
        <div className={styles.crumbs}>
          <Link href={`/${owner}/${name}`}>
            <a className={styles.rootLink}>{name}</a>
          </Link>
          <span className={styles.separator}>/</span>
          {crumbs.map((crumb, i) => {
            const isLast = i === crumbs.length - 1;
            const crumbPath = crumbs.slice(0, i + 1).join('/');
            const href = `/${owner}/${name}/tree/${branch}/${crumbPath}`;
            return (
              <>
                {isLast ? (
                  <span className={styles.crumbEnd}>{crumb}</span>
                ) : (
                  <>
                    <Link href={`/${href}`}>
                      <a className={styles.crumbLink}>{crumb}</a>
                    </Link>
                    <span className={styles.separator}>/</span>
                  </>
                )}
              </>
            );
          })}
        </div>
      )}
    </nav>
  );
}

export default RepoNavigation;
